### ISSUE TITLE
implement CSP metadata in base.html

### ISSUE THREAD

**Issue by rullmann** [alexandrevicenzi/Flex#104]
As per Mozilla Observatory the [CSP Header](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Content_Security_Policy) should be implemented. As this is a huge goal for the standard Pelican user we should at least implement it as metadata tag to prevent browsers from unloading unsafe scripts.

You may want to cherry pick my commit:
https://github.com/rullmann/pelican-theme-flex/commit/bcd1f0c5ad7e579bbc01dacb4080bd0b5e77689f

**Comment by alexandrevicenzi** [comment]
Adding this you can break someone else's theme based on Flex.

I don't see any use is this for a static blog generator.

**Comment by alexandrevicenzi** [comment]
If you think this would have a real value to someone else, please, reopen this issue.
