### ISSUE TITLE
Add subcategory support with 'subcategory' plugin

### ISSUE THREAD

**Issue by AmirMahmood** [alexandrevicenzi/Flex#106]
Hi,

First sorry for my bad English and thanks for this awesome theme @alexandrevicenzi.
I found [subcategory](https://github.com/getpelican/pelican-plugins/tree/master/subcategory) plugin that can adds support for subcategories in addition to article categories.
I think it's can be very useful for all users to have for example breadcrumb-style navigation to choose category or subcategories.

**Comment by alexandrevicenzi** [comment]
Flex has enough plugins support, I don't see any good in this plugin.
