### ISSUE TITLE
Issue of <pre><code>

### ISSUE THREAD

**Issue by peijunz** [alexandrevicenzi/Flex#108]
At [style.less line 204](https://github.com/alexandrevicenzi/Flex/blob/master/static/stylesheet/style.less#L204)

If there is
```htm
<pre><code>Some content here</code><pre>
```
in html, then the behavior is weird: There will be a preformatted box as well as a frame near the code. Unfortunately, for many html(e.g. generated from pandoc), this kind of tags combination will appear.

A solution is exclude this condition by small modification at Line 204

```css
*:not(pre) > code {
```
It will not hurt other cases.
Thank you!

**Comment by alexandrevicenzi** [comment]
So, are you writing HTML on your markdown file? If someone uses pure markdown this will never happen. If you mix things you can get weird behaviors.

It won't break anyone if these others only use pure MD. Well, this is a fix that could be done, even if breaks someone else :thinking:

**Comment by peijunz** [comment]
Well, I am writing a [jupyter notebook plugin](https://github.com/peijunz/ipynb2pelican) for pelican. It is using the html output of nbconvert, which converts [ipynb](http://jupyter-notebook.readthedocs.io/en/latest/) to other formats. 

From the [markdown_mistune.py](https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/markdown_mistune.py#L98) of nbconvert project, it is using `<pre><code>%s</code></pre>`. 

After I tested pandoc, I found pandoc is also producing `<pre><code>` tags. Although I am not familiar with web dev, I guess this may be a commonly used combination. At https://www.w3.org/TR/html5/grouping-content.html#the-pre-element, there is also an example code:

```
<p>This is the <code>Panel</code> constructor:</p>
<pre><code>function Panel(element, canClose, closeHandler) {
  this.element = element;
  this.canClose = canClose;
  this.closeHandler = function () { if (closeHandler) closeHandler() };
}</code></pre>
```

In github, it renders:

<p>This is the <code>Panel</code> constructor:</p>
<pre><code>function Panel(element, canClose, closeHandler) {
  this.element = element;
  this.canClose = canClose;
  this.closeHandler = function () { if (closeHandler) closeHandler() };
}</code></pre>

**Comment by alexandrevicenzi** [comment]
@peijunz This is now fixed.
