### ISSUE TITLE
Unescaped Characters in Summary Metadata

### ISSUE THREAD

**Issue by peijunz** [alexandrevicenzi/Flex#109]
## Occurance of bug
I wrote an article [here](https://raw.githubusercontent.com/peijunz/peijunz.github.io/src/content/Computer/intncpp.md), but the summary seems to be misbehaved. The generated html is broken:
```htm
<meta name="description" content="Also see gist #include <iostream> #include <cstdint> template<int N> struct least { static_assert(N < 9 &amp;&amp; N > 1, \" length="" beyond="" range="" 1<n<9!\");="" using="" int_="typename" least="" <n+1="">
```

Metadata is also leaked into `<body>`, which results in observable effect at the top of the web page.
```htm
::int_; }; template&lt;&gt; struct least&lt;1&gt; {using int_ = int8_t;}; template&lt;&gt; struct least&lt;2&gt; {using int_ = int16_t;}; template&lt;&gt; struct least&lt;4&gt; {using int_ …" /&gt;
<meta name="keywords" content="C++">
<meta property="og:site_name" content="Peijun's Thoughts">
...
```

## Mini Example
If the article is
```md
title: Use C++ Template to find int of least byte width
date: 2020-02-22

"Hello world!"
```

Then in the generated html, the description metadata is
`<meta name="description" content="" hello="" world!""="">`

## Summary
The reason of bug is the appearance of character `"` inside description. I am afraid we need to add some filter or something to escape these characters.

Thank you!

**Comment by peijunz** [comment]
## Possible solution
In another theme template [article.html](https://github.com/getpelican/pelican-themes/blob/master/pelican-bootstrap3/templates/article.html#L14)

There is another `escape` filter after the `striptags` filter. After applying this to both `article.html`  and `partial/og_article.html`, the problem is fixed.

**Comment by alexandrevicenzi** [comment]
Why is the article content in the meta tag?

The `escape` filter is missing, adding it fix the problem.

**Comment by alexandrevicenzi** [comment]
Fixed
