### ISSUE TITLE
Mixing French and English translations on the same page

### ISSUE THREAD

**Issue by Phyks** [alexandrevicenzi/Flex#117]
Hi,

I am posting on my blog sometimes in French and sometimes in English (so, there are posts in each language, but one post is never in both languages). My typical homepage looks like

First post (English)
Second post (French)
Third post (English)
etc.

For now, the Flex templates are in English, which is the default language. So below each title, I have "Posted on [english date] in [category]". I'd like this to be localized according to the lang of the article, but could not get it working. 

Using
```
DATE_FORMATS = {
    'en': '%B %d, %Y',
    'fr': '%d %B %Y',
}
```
I can change the date format, but I cannot find a way to change the lang of the "Posted on" template. Is it possible?

Thanks!

**Comment by alexandrevicenzi** [comment]
Pelican doesn't support this well unless you use a plugin called subsites.

Take a loon in the [docs](https://github.com/alexandrevicenzi/Flex/wiki/Supporting-multiple-translations-%28subsites%29).
