### ISSUE TITLE
External resources loaded

### ISSUE THREAD

**Issue by Phyks** [alexandrevicenzi/Flex#118]
Hi,

Most of the required resources for this theme are provided, which is really nice! However, I can see two queries being made:

1. One to https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic for the "Source Sans Pro" font. However, FontAwesome is already included and served locally, why not doing the same for this one and removing a call to googleapis?
2. Same for https://i.creativecommons.org/l/by-sa/4.0/80x15.png for the CC license icon, which additionnally returns a 301 to https://licensebuttons.net/l/by-sa/4.0/80x15.png. Why not just serving it locally as well?

Thanks!

**Comment by alexandrevicenzi** [comment]
1. Google Fonts is your friend: https://developers.google.com/fonts/faq
2. Don't know, I guess I didn't want to download all image licenses.

**Comment by Phyks** [comment]
1. Yes, still I do not want any of my readers to be forced to download content from Google fonts, that I could host myself. Maybe some setting could be used to trigger one behavior or the other?
2. As far as I can see, the only handled image is CC in the template.

**Comment by alexandrevicenzi** [comment]
1. Will you use Disqus? AdSense? GA? I don't see any reason to stop using Google Fonts.
2. Yes, it's only CC, but there are a lot of versions, so I guess it would be 16 (or more) extra images in this theme.

**Comment by Phyks** [comment]
1. Nope, I don't use any of these services. I just want to use Flex and Pelican for a dead simple static blog, that is no metrics, no comments, just the HTML files.
2. Ok, would you like a PR going in this direction?

**Comment by alexandrevicenzi** [comment]
1. We can include the font if Google allows it.
2. It could be done.

**Comment by Phyks** [comment]
1. According to https://developers.google.com/fonts/faq there should not be any problem.
2. Ok, I'll try to write something.

**Comment by Phyks** [comment]
Everything is included in https://github.com/alexandrevicenzi/Flex/pull/123.

**Comment by alexandrevicenzi** [comment]
@Phyks  you can set `USE_GOOGLE_FONTS` to `False` if you don't want to load any Google fonts. If so, it will fallback to other fonts.

**Comment by Phyks** [comment]
I'm not 100% sure but it seems `USE_GOOGLE_FONTS` discard the fonts and fallback to others, while it could simply use the same fonts and host them locally. That was the point of this issue (and MR).
