### ISSUE TITLE
Incomplete generated Pygments CSS files

### ISSUE THREAD

**Issue by Phyks** [alexandrevicenzi/Flex#119]
Hi,

Not sure if this is Flex's fault or Pygment's, but the generated CSS file are missing a lot of definitions. Typically, using `Monokai` theme, the `Text` elements are not dumped in the minified CSS files. Then, the text is rendered in black, which is not really readable (while it should be white). I guess this is because `Text` Pygments element does not have a defined class.

Also, when a value is undefined (typically `Generic.Prompt` in monokai style), Pygments uses some other value (not sure where it gets it from), which is not the case in Flex.

Here is a sample using their online formatter, which renders nicely:
http://pygments.org/demo/6363487/

The same sample with Flex renders as 
![screen](https://cloud.githubusercontent.com/assets/3856586/26027365/2a8e4e2a-380d-11e7-941e-63f310c2d8b2.png)

Thanks!

**Comment by alexandrevicenzi** [comment]
@Phyks I think it's a problem with Flex colors and Pygments colors. Pygments CSS aren't from Flex, I just use a tool to generate them.

We probably should fix this on Flex CSS, if there's a way, but it might break some other Pygments theme.

**Comment by Phyks** [comment]
When running `pygmentize -S monokai -f html > pygments.css`, I get more or less the same CSS file. It seems that `pygments` is not outputing the full CSS. :/

**Comment by Phyks** [comment]
Ok, after some debugging, it is coming from Pygments and I opened an issue on their bug tracker: https://bitbucket.org/birkenfeld/pygments-main/issues/1350/no-output-of-text-color-in-style.

Not sure how I could workaround it easily in the mean time, in Flex?

Thanks!

**Comment by alexandrevicenzi** [comment]
Just change the generated CSS file on Flex theme, no one changes that file, so it won't be a problem I think.

**Comment by alexandrevicenzi** [comment]
@Phyks can you try with the latest code from master? I think it's fixed now.
