### ISSUE TITLE
Align Images to Center with reStructuredText

### ISSUE THREAD

**Issue by alkhimey** [alexandrevicenzi/Flex#120]
The following snippet

    .. image:: xyz.png
       :align: center

Will emit the following html:

    <img class="align-center" src="xyz.png">

And the visual result will be an image aligned to the left.

The cause of the problem is that the ```align-center``` class does not exists in ```static/stylesheet/style.less```, only the ```img-center``` class exists.

The style of this class should be set according to the suggestion here: https://github.com/getpelican/pelican/issues/776

    .align-center {
       display: block;
       margin-left: auto;
       margin-right: auto;

I can do a PR, but I do not know how to minify the css to produce ```style.min.css```.

**Comment by alexandrevicenzi** [comment]
You can use gulp to minify or leave it to me.

**Comment by alkhimey** [comment]
My question is which tool do you use to minify the CSS?

If I try to use a different tool and commit the result, the minified version might be uncomparable, and there is no way to tell if the other minification method broke something or not.

**Comment by alexandrevicenzi** [comment]
I use [gulp](http://gulpjs.com/), as I said it before.

You can run `npm install` to install all dependencies and after run `gulp less` to generate the CSS.

As I said, it's better to leave it to me if you don't know how to do this. One day I may add to the wiki 😺 so it would be easy for those who want to change the LESS file.

**Comment by alkhimey** [comment]
@alexandrevicenzi see #120

**Comment by alexandrevicenzi** [comment]
Done.
