### ISSUE TITLE
Show ¶ only on hover?

### ISSUE THREAD

**Issue by peijunz** [alexandrevicenzi/Flex#122]
Currently, there is a ¶ following every heading. It really provides a good way to get the link of a heading, but I think it is a bit distracting. 

A way to solve the issue is showing the anchor "¶" only when hovered. In this way, if you are copying the text, ¶ will not be copied. As an example, the [official python tutorial website](https://docs.python.org/3/tutorial/interpreter.html) is showing anchor only when hovered.

This issue be resolved by https://github.com/peijunz/Flex/commit/359f5a5435994f0aa65833fd5cbb6ac34d3036ef (of my personal repo). If necessary, i can send a pull request on this.

**Comment by alexandrevicenzi** [comment]
I wouldn't like this on my personal blog, but it could be done using some settings, the thing is, we already have a lot of settings.
