### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by seveas** [alexandrevicenzi/Flex#13]
I don't actually have an issue :smile:

Just wanted to say thanks for this theme and its liberal license. As someone who can't design his way out of a beartrap, I've spent a long time finding a theme I like for my latest project ([click if you're interested](http://git.seveas.net)). This theme is pretty much perfect for what I need and it looks awesome. I may even use it in other projects.

**Comment by alexandrevicenzi** [comment]
Hi @seveas,

I feel good to know :smiley:  Your project looks good on Flex theme.

As you, I'm not a designer, but I tried to build my 1st theme.
