### ISSUE TITLE
Modified Date time

### ISSUE THREAD

**Issue by lam0r86** [alexandrevicenzi/Flex#131]
Hey, how can i change the modified Date time? 
its shown as: Last Modified: 2017-07-27 00:00:00+02:00
in og.html and og_article.html i didnt fond a way to change it!
greetz

**Comment by alexandrevicenzi** [comment]
Use Pelican metadata for this.

Title: Your Title Here
Date: 2016-07-25 08:00
Modified: 2016-07-25 08:00
