### ISSUE TITLE
Folder Shown as pages

### ISSUE THREAD

**Issue by lam0r86** [alexandrevicenzi/Flex#132]
Hey, 
i've got a folder in content called setup.
This folder is full of setupfiles in with .md extesion.
Now i want to show a list in pages(could be same as archives) with all of these files in content/setup/*.md folder!

Pretty nice would be to get those files ignored by normal archive :)

Hope anybody could help me! 
Ty for this nice Theme

Greetz

**Comment by alexandrevicenzi** [comment]
That's not a Flex bug.

If you want to hide some MD files use hidden metadata or find a way to do this with some Pelican settings.
