### ISSUE TITLE
Add support for Medium social link

### ISSUE THREAD

**Issue by sumnerevans** [alexandrevicenzi/Flex#135]
Currently, when a link to Medium is added, there is no background color:

![2017-08-18-12 21 39](https://user-images.githubusercontent.com/16734772/29472087-c5620ccc-840f-11e7-84e7-9af3c1a4af89.png)

I suggest that the background color `#00ab6b` be made the default background color for `a.sc-medium`. That color is the link color on medium.com. Here's what it looks like:

![2017-08-18-12 18 57](https://user-images.githubusercontent.com/16734772/29472067-b7cc9294-840f-11e7-8560-895849874ef5.png)

**Comment by alexandrevicenzi** [comment]
Can you send a PR?
