### ISSUE TITLE
Google Analytics tags are loaded in a deprecated place

### ISSUE THREAD

**Issue by rhyven** [alexandrevicenzi/Flex#137]
Hi Alexandre!

Google Analytics tags are now meant to be loaded in the <HEAD> tag [1].  I fixed this locally by moving the "if GOOGLE_ANALYTICS" lines in /templates/base.html.

[1] https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by alexandrevicenzi** [comment]
Hi @rhyven, this is a known issue. You can send a PR if you like.
