### ISSUE TITLE
Posts preview on main page.

### ISSUE THREAD

**Issue by kiddick** [alexandrevicenzi/Flex#14]
There is a cool option with preview of posts when they grouped by tag.

![1](https://cloud.githubusercontent.com/assets/9250239/11022488/cb8090c6-8671-11e5-83b4-7d01e41ca59d.png)
Is there any way to do the same on main page?
![2](https://cloud.githubusercontent.com/assets/9250239/11022489/cb9bb338-8671-11e5-932b-c2d75ecd7c68.png)

Thanks in advance!

**Comment by alexandrevicenzi** [comment]
I think there's one of Pelican settings that could work. By now, I know there's a bug with this feature.

I'll try to fix this soon, but I'm to busy.

**Comment by kiddick** [comment]
Thanks for reply.
Check this https://hathcock.me/.
Seems it is ok here.
@hathcock could you please share with us setting for subject of topic?

**Comment by alexandrevicenzi** [comment]
@kiddick he made a wrap at index.html. You can set `{% set summarize = True %}` to get it working.

[See here](https://github.com/hathcock/hathcock.me/blob/pelican/flex/templates/index.html).

**Comment by hathcock** [comment]
Yep, obviously the quick-n-dirty fix to get the visually pleasing main page snippets, but it works.

**Comment by alexandrevicenzi** [comment]
@hathcock and @kiddick I will add an setting for that :kissing_heart:

**Comment by alexandrevicenzi** [comment]
@kiddick and @hathcock you can use `SUMMARY_MAX_LENGTH` pelican setting ou also `summary` metadata tag.

These are pelican default configs, now it just works :smile:
