### ISSUE TITLE
How to use # as a start of command in code blocks

### ISSUE THREAD

**Issue by Wobak** [alexandrevicenzi/Flex#143]
Hi,

Sorry this might not be a direct issue, but I'm trying to make sense of markdown and pelican :)

I love your theme and I have set it up on my page to start writing articles. My articles are mainly about Linux stuff, and most of the linux stuff I do needs root. So my examples are often in the following output : 

```
root@computer ~ # my command
some result
```

Except that when I do that, using your theme, everything after the # is greyed and looks like a comment. Is there a way to change that behaviour ?

Thanks a lot !

**Comment by alexandrevicenzi** [comment]
You need to specify what language your code is, please, refer to [pelican documentation](http://docs.getpelican.com/en/3.6.3/content.html#syntax-highlighting) for this.

**Comment by Wobak** [comment]
Hi,

In that case, I tried to use ``` bash as a language code, but in there, # still starts a comment (which is the way in real life, but except for the command prompt), and therefore is still grey and italic, which doesn't really stand out.

What language pygment would you suggest to illustrate such ?

Thanks, 
Thibaut

**Comment by alexandrevicenzi** [comment]
Maybe PowerShell, check [this link](http://pygments.org/languages/) to see all languages supported.
