### ISSUE TITLE
Upgrade Font Awesome and add Mastodon Social icon

### ISSUE THREAD

**Issue by pawelngei** [alexandrevicenzi/Flex#154]
I'll gladly submit a PR with that if you're okay with upgrading FA to 5.1.0.

**Comment by pzelnip** [comment]
@pawelngei I'd be interested in seeing what you've come up with.  I use a custom theme based on Flex, and I'd love to have FA 5, but my CSS skills are not up to snuff for figuring out what's involved in changing the theme to get it to work with FA 5.

**Comment by pawelngei** [comment]
I already applied it for my own blog at https://alxd.org/ . There's a lot which can be done with CSS, but for starters I:
 - upgraded Font Awesome to the latest (messing the templates a little in the meantime)
 - increased the font size
 - added the Mastodon button
 - decreased the buttons' "jump"

I'll link to a proper fork on Github in a moment.

**Comment by pawelngei** [comment]
Created https://github.com/alexandrevicenzi/Flex/pull/156 with the changes. They can be further optimized, but that's what I needed for myself.

**Comment by alexandrevicenzi** [comment]
@pawelngei FA 5 is a good idea. Sorry for the late reply.

**Comment by pawelngei** [comment]
Thanks for merging!
