### ISSUE TITLE
Site is not going live

### ISSUE THREAD

**Issue by rakshitsoral** [alexandrevicenzi/Flex#159]
Hi,

I have tried my best to make rakshitsoral.github.io up and running. I have cloned pelican-themes and changes my `THEME` variable to "pelican-themes/Flex". Also, I changed `SITEURL` to `'https://rakshitsoral.github.io'`.

After comitting changes and trying to publish the site by using
```
(staticsite) $ git add .
(staticsite) $ git commit -m "first published version"
(staticsite) $ git push origin master
```
I am still not able to publish the site to github pages. However, it's up and running in my http://localhost:8000/

Anyone please help?

**Comment by pawelngei** [comment]
Hey!

Did you follow https://fedoramagazine.org/make-github-pages-blog-with-pelican/ ? I can't see a repository containing the `output` on your profile. It's supposed to be a submodule of your `src` repository, as in:

> To create your Github user page, log in to Github and create two new repositories, username.github.io-src and username.github.io, as explained on Github pages. (Use your Github username for these repositories.) The username.github.io-src repository will hold the sources of your blog and the username.github.io repository will contain the output HTML files Pelican generates. To add the output directory as a submodule, initialize it with a README file.

Github pages need to find an `index.html` at the root of the repository named `rakshitsoral.github.io`, and your repo doesn't have one. Just clone it to a repo `rakshitsoral.github.io-src` and add the output folder as a `rakshitsoral.github.io` repo.

**Comment by rakshitsoral** [comment]
Hi,

I followed this handy series pf blogs by pythonundergradforbeginners: https://pythonforundergradengineers.com/how-i-built-this-site-1.html

I must say, i had to refer some different sources as well as the one i mentioned doesn't seemed to work on my computer. 

And the repo has index.html in the output folder rakshitsoral.github.io/output. Have you seen it?

**Comment by pawelngei** [comment]
@rakshitsoral , your repo needs to have `index.html` in root (base folder). Try doing what the tutorial I linked says - and you'll see it will work.

**Comment by alexandrevicenzi** [comment]
@rakshitsoral check [Pelican Blog](https://github.com/getpelican/pelican-blog) for a reference.
