### ISSUE TITLE
Social media icons broken

### ISSUE THREAD

**Issue by edmondchuc** [alexandrevicenzi/Flex#162]
Hi I am trying to use the social media icon for GitHub and it is not rendering correctly.

My `pelicanconf.py` file has:

```python
SOCIAL = (
    ('github', 'https://github.com/alexandrevicenzi/Flex'),
    # ('rss', '/blog/feeds/all.atom.xml'),
)
```

Any idea?

**Comment by dmark** [comment]
Can you provide a screencap of what it looks like now?

**Comment by edmondchuc** [comment]
Hi @dmark I'm not sure how to reproduce the error again. The link must have been broken or something at the time. It has fixed itself. 

The broken icon looked something like  [this](https://imgur.com/a/Qp7DPsz).

**Comment by alexandrevicenzi** [comment]
Font Awesome was updated, maybe it was cached somewhere and for a couple of minutes, it appeared to be broken.
