### ISSUE TITLE
Home button not working properly

### ISSUE THREAD

**Issue by pogoetic** [alexandrevicenzi/Flex#164]
I'm having an issue with the home button. My issue is that even when `SITEURL` is set correctly, the `HOME` link at the top will change its path to whatever page you happen to be on. The blog is located here: https://pogoetic.github.io/

I have tried a number of things but cannot seem to figure out the issue. Please help.

_Originally posted by @pogoetic in https://github.com/alexandrevicenzi/Flex/issues/87#issuecomment-443596083_

**Comment by alexandrevicenzi** [comment]
Your SITE URL is not set.

https://github.com/pogoetic/pogoetic.github.io/blob/dev/publishconf.py#L13

**Comment by pogoetic** [comment]
You are absolutely right. I did not realize the publishconf overwrote the pelicanconf. Thank you for pointing that out! Your template is great by the way!
