### ISSUE TITLE
Page sort order not well documented and differs from Pelican configuration

### ISSUE THREAD

**Issue by ricekab** [alexandrevicenzi/Flex#170]
## Context

By default, pages are ordered by name. When this is not wanted a custom sort order can be defined.

[Pelican documentation](http://docs.getpelican.com/en/3.6.3/settings.html#ordering-content) specifies `PAGE_ORDER_BY` as the default setting for this (since 3.6 I believe). Flex uses `PAGES_SORT_ATTRIBUTE` for this functionality. I also couldn't find this documented on the wiki.

## Proposed solution

A. Deprecate `PAGES_SORT_ATTRIBUTE` and  support `PAGE_ORDER_BY` in `templates\base.html`.

B. Keep as-is and document page ordering mechanism in the wiki.

**Comment by alexandrevicenzi** [comment]
Fixed by #171
