### ISSUE TITLE
Add formspree (ability to collect emails) form on the sidebar

### ISSUE THREAD

**Issue by filipgeppert** [alexandrevicenzi/Flex#175]
Problem: 
Ability to engage users through newsletter. 

Possible solution:
Add [formsperee](https://formspree.io/) form for users to type their email. 

Advantages:
- easy to implement (example of implementation [here](https://filipgeppert.com/))
- free

Disadvantages:
- form needs to be validated on every static site, so any time new post is submitted, form needs to be validated for this url. But maybe there is a workaround that I don't know about.

I wrote the implementation [here](https://filipgeppert.com/) that adds newsletter form on the sidebar. It modifies:
- base.html
- pelicanconfig.py (new variable with author email)
- style.min.css -> some styling for form 

Let me know what you think and if you think it's a good idea, then I will open a PR.
Cheers!

**Comment by alexandrevicenzi** [comment]
@filipgeppert AddThis plugin does not solve this problem? They have a similar feature, never used, so I have no idea if it actually works with Flex.

**Comment by filipgeppert** [comment]
@alexandrevicenzi Indeed, AddThis has this option, but it doesn't work when a user has ad blocker turned on.

**Comment by alexandrevicenzi** [comment]
@filipgeppert but that's not Flex problem, even Google plugins will fail if AdBlock is enabled.

If you find an easier way to validate the form I would be OK with, but for now looks like it's too painful for someone to use this plugin.

**Comment by filipgeppert** [comment]
True, I will write to formspree and as if there is any workaround.

**Comment by alexandrevicenzi** [comment]
This change makes no sense any more, one can create a contact page, or use the plugins already available in the theme.

**Comment by Kentoseth** [comment]
Hey @filipgeppert can you please share the changes you made to your HTML files to get the form embedded?

I tried to copy your code from your website and I have a form, but I don't have your styling.
