### ISSUE TITLE
Integration with pelican_comments

### ISSUE THREAD

**Issue by giomasce** [alexandrevicenzi/Flex#177]
Hi,

I have added basic integration with [pelican_comments](https://github.com/bstpierre/pelican-comments) in [my fork of Flex](https://github.com/giomasce/Flex/commit/ad0f985841875a2685dd9c0378c4b75c312df592). Would you consider it interesting to include it in the main release?

Thanks for the great theme, Giovanni.

**Comment by alexandrevicenzi** [comment]
@giomasce could be done, the only problem is how to add new comments, looks like there's no standard way in this plugin.

I know that some people don't like Disqus, so an alternative would be good.

**Comment by NikolaiT** [comment]
I am also interested in this.

**Comment by sumnerevans** [comment]
I'm planning on integrating [Isso](https://posativ.org/isso/) into my fork, and I'll submit a PR if there is interest in integrating it directly into this repo.

**Comment by alexandrevicenzi** [comment]
I guess Isso solves this better. Closing it for now.
