### ISSUE TITLE
Installation on SiteGround

### ISSUE THREAD

**Issue by earl-e-bird** [alexandrevicenzi/Flex#179]
Hi all, 
I was wondering if you could help me with the installation process on sites like SiteGround. This theme is not recognised by their proprietary theme builder (missing .css file) and needs a work around. I'm new to building websites but quickly realised that almost all of the free and suggested themes are increadibly restrictive. If you could help that would be absolutely amazing. Many thanks in advance.
Earl-e-bird

**Comment by alexandrevicenzi** [comment]
@earl-e-bird Why use such service focused on Wordpress when you can host it for free on Git Hub Pages?

**Comment by earl-e-bird** [comment]
I've never created a homepage in my life and am very new to all of this. Didn't know I could host my own homepage on Git Hub. Thank you for that idea Alexandre. I'll do some research on this but feel free to point me in the correct direction :) Much appreciated.

**Comment by alexandrevicenzi** [comment]
You can probably start [here](https://pages.github.com/) and [here](http://docs.getpelican.com/en/3.6.3/tips.html#publishing-to-github).
