### ISSUE TITLE
Inconsistent Sidebar Size

### ISSUE THREAD

**Issue by groverj3** [alexandrevicenzi/Flex#181]
Hey there,

I've noticed a rather annoying little bug. It seems that the sidebar is sized slightly differently depending on what's in the main window. I thought this might've been because I forked the master branch, rather than one of the tagged releases, but switching to the most recent release didn't change anything. This is also apparent in several others' websites made with the Flex theme as well.

You can most easily see what I'm talking about on my [github.io page](https://groverj3.github.io) (WIP) by switching between the Home and Projects (or Blog) pages.

I'm no expert at css and html, but I was able to "fix" this by changing the sidebar size to be relative to text size rather than % of the window size. This broke the scaling though when the window is resized.

I figured I'd bring this to your attention since I didn't see a related issue and ask if you had any advice for fixing this in a "correct" way. Though, I know that it's no longer under active development.

**Comment by alexandrevicenzi** [comment]
@groverj3 probably some CSS is off, something being miscalculated or getting some extra padding from somewhere.

If you know how to fix send a patch, otherwise it might take me a while to debug and find a solution.

**Comment by systemexitzero** [comment]
You may be seeing the sidebar shrink ~20px whenever your pages have enough content to require a scrollbar. Does adding `main { overflow-y: scroll; }` to your `custom.css` stop the sidebar from jumping?

**Comment by groverj3** [comment]
Wow, sometimes it's the most obvious things...

That is probably exactly what's going on. When I get a spare moment I'll just this a shot.

**Comment by groverj3** [comment]
Just tried this. Forcing a scrollbar to be visible like that doesn't seem to work in Chrome on either linux or windows, but does work in Firefox.

**Comment by groverj3** [comment]
Out of curiosity, I switched the widths and heights to vw and vh units instead of %. This actually worked in combination with overflow-x: hidden. It makes sense that when a vertical scrollbar was needed it would now cause the need for horizontal scrolling.

**Comment by alexandrevicenzi** [comment]
Fixed in #182.
