### ISSUE TITLE
Add support for admonitions

### ISSUE THREAD

**Issue by johanfleury** [alexandrevicenzi/Flex#187]
Hey @alexandrevicenzi, thank you for Flex, it's a great theme.

I just found out it is lacking support for admonition and I thought I could make a PR. I know Flex is not under active development anymore but I think it's a great feature that's missing.

You probably have a stronger opinion than I do about how admonition should look in Flex so let's discuss it before creating a new PR.

Here is how admonitions look at the moment (pretty ugly due to lack of CSS): ![admonition in Flex](https://up2sha.re/media/raw/dz28dY.png?token=U4A%2FuBw8Lb0O0PoRbEC9k7HPs%2FaEIdst).

Here is how they could look (with CSS found in https://github.com/Pelican-Elegant/elegant/issues/216): ![admonition in Flex with CSS](https://up2sha.re/media/raw/Q7RS72TE6XmuyN8974.png?token=G5K0g5S7YZj4%2BEIrURHFsdPm494wEP4L)

I think this is a small change that could make Flex better, what do you think?

**Comment by alexandrevicenzi** [comment]
@johanfleury I think that could be useful, feel free to send a PR.

I believe we only need extra CSS right?

**Comment by johanfleury** [comment]
Yep that's right. I'll do the PR then :)

**Comment by alexandrevicenzi** [comment]
PR merged.
