### ISSUE TITLE
Add support to webassets plugin

### ISSUE THREAD

**Issue by mauricioabreu** [alexandrevicenzi/Flex#19]
Would you like to have webassets plugin support for Flex?
I have it on my project (https://github.com/mauricioabreu/blog). If so, tell me so I can create a pull request soon. 
Thanks for this beautiful theme. :-)

**Comment by alexandrevicenzi** [comment]
I think you can send a PR. I'll take a look after.

**Comment by alexandrevicenzi** [comment]
As mentioned in #40, I'm closing this issue.
