### ISSUE TITLE
Example Site is Broken

### ISSUE THREAD

**Issue by mholiv** [alexandrevicenzi/Flex#190]
The https://flex.alxd.me/blog/ example site contains many links that point to resources on http://localhost:8000

To reproduce this:
1. Make sure no local server is running at http://localhost:8000
2. Goto https://flex.alxd.me/blog/
3. Click on "Contact"

What you expect:
To to the contact page hosted under flex.alxd.me

What actually happens:
You are sent to http://localhost:8000/pages/contact.html#contact

**Comment by alexandrevicenzi** [comment]
Thanks, example is up and running again.
