### ISSUE TITLE
Upper Case for the content and links

### ISSUE THREAD

**Issue by jiefengsun** [alexandrevicenzi/Flex#197]
{% for name, link in LINKS %}
          <li><a href="{{ link }}" target="_blank">{{name|title}}</a></li>
![image](https://user-images.githubusercontent.com/31747948/76697772-09c52f80-6661-11ea-8e5a-ae2348dd52e8.png)

It seems that the LINKs cannot be Upper case.

**Comment by alexandrevicenzi** [comment]
Yes, you can't, unless you change the CSS for your blog, this is not done in python or jinja, but with CSS text-transform property.
