### ISSUE TITLE
Social 'email' logo not appearing

### ISSUE THREAD

**Issue by jasongtz** [alexandrevicenzi/Flex#2]
Added `('email', 'mailto:name@mydomain.com'),` to SOCIAL. All the others seem to be working, but mail is a blank blue circle, not a logo.

Apologies, bug or feature?

<img width="336" alt="screen shot 2015-07-24 at 13 08 17" src="https://cloud.githubusercontent.com/assets/10981911/8874099/77c46e8c-3205-11e5-8bd1-ffffd95b581f.png">

Thanks for the theme, it's great!

**Comment by jasongtz** [comment]
After looking into it more, I think it's because the Font Awesome email icon is called 'envelope-o'. Changing `email` to `envelope-o` in the config file fixes the icon, but breaks the background colour, (presumably in the CSS). I've played around with it but don't have much experience with CSS - if I figure out how to fix it, I'll submit a pull request.

**Comment by jasongtz** [comment]
Fixed in pull request #3.

**Comment by tyleraland** [comment]
Patiently anticipating this pull request to be merged.  Thanks for the fix jasongtz and lots of thanks alexandrevicenzi for the great theme!

**Comment by alexandrevicenzi** [comment]
PR accepted. Thanks for found this.
