### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by sumnerevans** [alexandrevicenzi/Flex#201]
It would be great if Flex had a dark mode option. Here are some things that I think are critical for a good dark mode:

* Automatic detection of browser theme preference (if the browser or OS provides it). This functionality should not require JavaScript to be enabled.
* An option to allow the user to override the detected theme. It is fine if this functionality requires some JavaScript.
* Allow different pygments themes for dark/light mode. This functionality should not require JavaScript to be enabled.

I've begun work on this on my fork which I am using on my website. Here's an example page which demonstrates all of these: https://sumnerevans.com/2020/respect-theme-preferences.html#respect-theme-preferences. It detects the browser/OS theme by default. It also all has links in the footer to change the theme. And when you change the theme, the code blocks are styled differently.

**Light mode:**
![Screen Shot 2020-04-09 at 09 40 43](https://user-images.githubusercontent.com/16734772/78913420-3729b100-7a46-11ea-81b4-b7f721cea0ab.png)

**Dark mode:**
![Screen Shot 2020-04-09 at 09 37 03](https://user-images.githubusercontent.com/16734772/78913448-401a8280-7a46-11ea-98e4-4bc6ba513eeb.png)

If this is something that would be of interest to integrate into the Flex theme, then I'll work on polishing this up for general use.

**Comment by Dorson** [comment]
@sumnerevans Impressive job :1st_place_medal:  :+1: 

Did a similar code with a demo in here:
https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

My version uses the html tag as the root element for color variables, instead of the body one. Helps to overwrite automatic settings, if the user wants to do so.


Great work !

**Comment by alexandrevicenzi** [comment]
Feel free to send a PR.
