### ISSUE TITLE
Update documentation for JINJA_EXTENSIONS

### ISSUE THREAD

**Issue by NicoPy** [alexandrevicenzi/Flex#204]
JINJA_EXTENSIONS has been deprecated and replaced by JINJA_ENVIRONMENT.

It is used like this :
JINJA_ENVIRONMENT = {
    'extensions': ['jinja2.ext.i18n']
}

**Comment by sumnerevans** [comment]
The wiki is publicly editable. You can update the wiki with the correct configuration.

**Comment by alexandrevicenzi** [comment]
Wiki was updated.
