### ISSUE TITLE
Bug in CSS with placement of "Newer Posts" button

### ISSUE THREAD

**Issue by marcelhuth** [alexandrevicenzi/Flex#21]
Hi,
it seems that there is a bug in CSS with placement of "Newer Posts" button on index.html pages. The issue only applies when there is only one article on the page.

<img width="712" alt="bildschirmfoto 2015-12-22 um 12 15 16" src="https://cloud.githubusercontent.com/assets/9551108/11954077/b5819954-a8a5-11e5-9b7a-32688383ee4b.png">

Unfortunately I'm not the CSS expert to figure out the error on my own :(

I did change a couple of things in my fork of the repo, but AFAIK non of the changes should have changed that property. Probably you can recreate the issue? I'll try to fix that during the next days.

Thanks for your help in advance!

Cheers,
Marcel

**Comment by marcelhuth** [comment]
I think I figured out a quick'n'dirty workaround. In pagination.html just added a
```html
<div style='clear:both'></div>
```
That makes sure the button is placed before the `hr`

**Comment by alexandrevicenzi** [comment]
Hi @marcelhuth,

Could you provide OS and browser version?

**Comment by marcelhuth** [comment]
OS is MacOS 10.11.2 with browsers Chrome 47 and also with Safari 9.0.2
