### ISSUE TITLE
Are the double bars in the menu intentional?

### ISSUE THREAD

**Issue by sumnerevans** [alexandrevicenzi/Flex#211]
Is it intentional that there are double bars between the items in the menu bar? Also, it appears that there is no margin/padding between the bars that are between "HOME" and "ARCHIVES".

![image](https://user-images.githubusercontent.com/16734772/79295082-0bb72400-7e95-11ea-842e-37054af024ca.png)

I think it looks better if it's a single bar:
![image](https://user-images.githubusercontent.com/16734772/79295204-5a64be00-7e95-11ea-95a6-77243a2b9ae3.png)

or consistent double bars:
![image](https://user-images.githubusercontent.com/16734772/79295249-78cab980-7e95-11ea-8352-2f988512edad.png)

**Comment by alexandrevicenzi** [comment]
You can make it single I guess, looks better than double.

**Comment by sumnerevans** [comment]
Ok, I've updated the PR #212 accordingly.
