### ISSUE TITLE
Tipue Search integration doesn't include tipuesearch_content.js

### ISSUE THREAD

**Issue by sumnerevans** [alexandrevicenzi/Flex#214]
According to the documentation for the `tipuesearch` plugin: https://github.com/getpelican/pelican-plugins/tree/master/tipue_search#how-to-use, the following must be included if using `tipuesearch`:
```
<script src="{{ SITEURL }}/tipuesearch_content.js"></script>
```
however the existing integration does not include that file.

**Comment by alexandrevicenzi** [comment]
I did not implement this, so it may be buggy, as well I don't use Tipue Search.
