### ISSUE TITLE
Translated links in main nav have extraneous whitespace

### ISSUE THREAD

**Issue by sumnerevans** [alexandrevicenzi/Flex#216]
When the `<a>` tags that are translated (Home, Atom, and RSS) get rendered, additional whitespace is added. This causes some browsers to render a space after the text, which messes up styling of the nav bar. For some reason I didn't catch this issue when I was working on #212 

```
    <nav>
      <a href=".">    Home
</a>

      <a href="/archives.html">Archives</a>
      <a href="/categories.html">Categories</a>
      <a href="/tags.html">Tags</a>


    </nav>
```

**Comment by alexandrevicenzi** [comment]
The problem is [here](https://github.com/alexandrevicenzi/Flex/blob/master/templates/base.html#L3).
