### ISSUE TITLE
add support for pelican-toc plugin

### ISSUE THREAD

**Issue by qian-gu** [alexandrevicenzi/Flex#218]
I think it would be great if Flex can generate a table of content for each article, beacuse most technical blogs will be more easy to read with a table of content.

`pelican-toc` plugin is pretty good for me, I have made a little update in articlce.html to support it.

The live demo is here, ignoring the section number generated by `section_number` plugin.

http://guqian110.github.io/posts/python/pep8_in_practice.html

**Comment by alexandrevicenzi** [comment]
你好, sounds good, as long as you can disable on specific posts.

For example, it could be part of post meta, as `toc: True` or something like that.

**Comment by guqian110** [comment]
> 你好, sounds good, as long as you can disable on specific posts.
> 
> For example, it could be part of post meta, as `toc: True` or something like that.

ok, I will try it later.

**Comment by guqian110** [comment]
> 你好, sounds good, as long as you can disable on specific posts.
> 
> For example, it could be part of post meta, as `toc: True` or something like that.

I found that `pelican-toc` has already support a metadata `toc_run:true` to enable generating a TOC.

I just need set `toc_run: false` in pelicanconf.py and it will not generating a toc for any posts, people can turn it on for specific posts by using `toc_run:true` in their markdown files, so I think I needn't do anything else except for integrating the plugin into article.html.

Let me know if I'm right, and I will send a PR for it.

**Comment by alexandrevicenzi** [comment]
Sounds good to me.

**Comment by lpenaud** [comment]
Interested by a table of content like Wikipedia has ?

**Comment by alexandrevicenzi** [comment]
The one in there is kinda ugly, there was a PR for toc, but it seems we have not yet found a good place or style for toc.

I'm open to more ideas, I suggested something [like this](https://mmistakes.github.io/minimal-mistakes/layout-table-of-contents-post/).

Still, toc only makes sense to huge posts, and not everyone writes long posts. I find only useful where you can navigate to sections, but articles, DIY and similar stuff are usually connected, you can't skip a section of it.

**Comment by lpenaud** [comment]
Okay, I will try to do something, maybe I can write a plugin which use metadata to specify if the article need a toc (an default option to ?).

**Comment by lpenaud** [comment]
I starting to work on toc style with a little bit of JavaScript.
For now this only concerns the `contents` reStructuredText directive.

Then, with this brute text: 

```rst
.. Table of content
.. contents:: Sommaire
    :depth: 3

.. Some contents...

.. Local table of contents
.. contents:: Sous-sommaire
    :local:
```

it's will generate that:
![Table of contents](https://user-images.githubusercontent.com/18645983/80916995-7d7be280-8d5c-11ea-98ff-d64f94752759.png)
![Local table of content](https://user-images.githubusercontent.com/18645983/80917040-bd42ca00-8d5c-11ea-8cce-1e48f49260a3.png)

With the button (➖, ➕), you can toggle the display of the list of contents.

**Comment by alexandrevicenzi** [comment]
I would use pelican-toc plugin that already exists and just grabs what is in the page.

The only missing thing is the styles and where to put it in the theme.

**Comment by lpenaud** [comment]
Pelican-toc plugin integration:

![image](https://user-images.githubusercontent.com/18645983/81735552-7f991c00-9495-11ea-8ad4-67e34605168b.png)

![image](https://user-images.githubusercontent.com/18645983/81735392-4660ac00-9495-11ea-8f24-a5a84bc0121e.png)

**Comment by alexandrevicenzi** [comment]
Looks promising, both options are valid I think, it could be configured where you want to place, like top, or right.

**Comment by lpenaud** [comment]
Ok, I add `TOC_FLOAT` variable to set the TOC position.

* By default TOC is placed to the top
* `TOC_FLOAT = 'right'` to place TOC to the right
* `TOC_FLOAT = 'left'` to place TOC to the left

Add some breakpoints too (according to Bootstrap ones) to avoid this (`min-width: 768px`): 
![image](https://user-images.githubusercontent.com/18645983/81845901-8a18eb80-9551-11ea-8e0c-128c8018e03f.png)

So, now it's like mobile version:
![image](https://user-images.githubusercontent.com/18645983/81846325-322eb480-9552-11ea-8242-2cf4b3b630d9.png)

Last but not least extra large devices (large desktops, 1200px and up) don't limit TOC maximum width.

**Comment by alexandrevicenzi** [comment]
TOC on mobile looks nice, but the desktop one that wraps around text seems weird IMHO.

**Comment by alexandrevicenzi** [comment]
Closing this as Pelican Markdown has TOC already, no plugins are needed.
