### ISSUE TITLE
Figure style

### ISSUE THREAD

**Issue by lpenaud** [alexandrevicenzi/Flex#224]
Hi, I would like to send a PR to add some style to figure element.

## Problematic
Figure element is not mentioned in `style.less`.

## Proposed solution
Add style to theses class: 

* `div.figure`
  * `img`
  * `p`
  * `p.caption`
  * `div.legend`
* `div.figure.align-left`
* `div.figure.align-center`
* `div.figure.align-right`

#### Light theme
![light](https://user-images.githubusercontent.com/18645983/80535595-5bbbdd80-89a1-11ea-8541-fc488d26fa0f.jpg)

#### Dark theme
![dark](https://user-images.githubusercontent.com/18645983/80535642-6c6c5380-89a1-11ea-96a0-729cc449eeae.jpg)

Best regards,
Loïc

**Comment by alexandrevicenzi** [comment]
Hi,

Sounds reasonable, feel free to send a PR.

**Comment by alexandrevicenzi** [comment]
Fixed by #225.
