### ISSUE TITLE
Development: update / add gulp tasks

### ISSUE THREAD

**Issue by lpenaud** [alexandrevicenzi/Flex#226]
Hi,
I modify dark theme in a previous PR #225, and `USE_LESS` variable doesn't work with `dark-theme.less`. Plus, now Flex have a JavaScript file which interact with the style of the page.

## Problematic
Dark theme files aren't refresh when you use `USE_LESS` variable.
Theses files should be watch:

* `static/stylesheet/dark-theme.less`
* `static/dark-theme/dark-theme.js`

## Proposed solution
Since `USE_LESS` variable is design for testing purposes, why not to watch files and use not minify versions ? Then replace `USE_LESS` variable by `NOT_MINIFY` (or something like that) and add watch task to gulp like:

```js
gulp.task('watch-less', function () {
    return gulp.watch("static/stylesheet/*.less", gulp.task("less"));
});

gulp.task('watch', gulp.series('default', 'watch-less'));
```

## Optional

* Write more modern JavaScript in gulpfile using arrow function, use `const` instead of `var`.
* Add `watch` script in `package.json` to call `watch` gulp task.

**Comment by alexandrevicenzi** [comment]
@sumnerevans want to take a looks as you did the dark theme?

**Comment by lpenaud** [comment]
In my example, I forget to watch JavaScript files. You can use [watch-task branch on my repo](https://github.com/lpenaud/Flex/tree/watch-task) to test it if you want.
```js
gulp.task('watch-less', function () {
    return gulp.watch('static/stylesheet/*.less', gulp.task('less'));
});

gulp.task('watch-js', function () {
    return gulp.watch('static/js/*.js', gulp.task('uglify'));
})

gulp.task('watch', gulp.series('default', gulp.parallel('watch-less', 'watch-js')));
```

**Comment by haplo** [comment]
@alexandrevicenzi I created a PR from @lpenaud's branch, it's working for me. I actually added a watch task locally before discovering this issue and @lpenaud's work. I think it's a good idea to merge it as it's backwards-compatible.

**Comment by haplo** [comment]
@lpenaud I have merged your changes in my fork of Flex that I called Reflex. I'm going to integrate more changes that have been pending on Flex, then make a release of the theme.

**Comment by alexandrevicenzi** [comment]
@haplo I like the name, but if anyone asks to be a contributor to this project, I can give permission to merge MRs.

Unfortunately, I don't have enough time to take of everything, and as I switched to Hugo a long time ago, this tame has been kinda stale for a while, as many still use it, I would like to keep it alive with contributions for others.

**Comment by haplo** [comment]
> @haplo I like the name, but if anyone asks to be a contributor to this project, I can give permission to merge MRs.
> 
> Unfortunately, I don't have enough time to take of everything, and as I switched to Hugo a long time ago, this theme has been kinda stale for a while, as many still use it, I would like to keep it alive with contributions for others.

I wish you would have replied before I went ahead and put the effort into the fork, I would have accepted your offer then. At this point I think I will keep Reflex, as I'm already working on some backwards-incompatible visual changes. Of course feel free to merge back any changes you find useful, most of the theme will remain compatible.

Thank you very much for Flex!

**Comment by alexandrevicenzi** [comment]
@haplo it's ok to fork, that's the open source spirit :)

I'm also planing some changes in the codebase, things are a bit messy to maintain.

**Comment by haplo** [comment]
Hi @alexandrevicenzi, it's been a long time!

After a long pause I'm putting some more work on [Reflex](https://github.com/haplo/pelican-theme-reflex). For now the codebase should be pretty similar to Flex, in case there are any changes you might want to pull in.
