### ISSUE TITLE
Pure admonitions don't have any styling

### ISSUE THREAD

**Issue by sumnerevans** [alexandrevicenzi/Flex#229]
The following rST

```
.. admonition:: Prerequisites

    For this article, I assume that you...

    * Already have basic competency in Git and GitLab (although I don't assume
      knowledge of GitLab CI/CD).
    * I assume that you already have a Pelican site setup. If you don't, the
      `Pelican Documentation`_ is really good. The ``pelican-quickstart``
      command works great, and will help you easily get started with your site.

    .. _Pelican Documentation: http://docs.getpelican.com/en/stable/quickstart.html
```

currently produces:

![2020-05-03-16:47:12](https://user-images.githubusercontent.com/16734772/80927884-e44dcb80-8d5d-11ea-8d60-34b0cd5a8314.png)

I suggest that it uses the "tip" color, without the tip icon. For example:

```
.. admonition:: This is an admonition

   Foo bar baz

.. tip::

   Foo bar baz
```

would become:

![2020-05-03-16:50:54](https://user-images.githubusercontent.com/16734772/80927932-4a3a5300-8d5e-11ea-8288-af4ee9710795.png)

**Comment by alexandrevicenzi** [comment]
Don't know, it does not seem right to me to change.

There are some docs [here](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions) about Generic Admonition, as well as styling looks [here](https://pythonhosted.org/sphinxjp.themes.basicstrap/sample.html#admonitions-docutils-origin).

`admonition` is generic, does not specify anything, if it should have any color it should not be the color of some another type.

@johanfleury WDYT?

**Comment by johanfleury** [comment]
I can’t figure what a use case for a generic admonition could be, let alone if it would be the same for everyone so I would let end users decide by using custom CSS on their side.

**Comment by alexandrevicenzi** [comment]
If it's to add some style, I would at least make something not popular, to force use something else. Probably a good idea would be some grayish color.

**Comment by sumnerevans** [comment]
Generally, the reason for using a blank *admonition* rather than one of the other ones is that you can have a custom title. I think that grey sounds good. What do you think of this?

**Light Mode**

![2020-05-07-09:45:52](https://user-images.githubusercontent.com/16734772/81315465-9085ff80-9047-11ea-8cb2-0525c8fe57b6.png)

**Dark Mode**

![2020-05-07-09:45:40](https://user-images.githubusercontent.com/16734772/81315483-94b21d00-9047-11ea-8fee-ae46c0f05e57.png)

**Comment by alexandrevicenzi** [comment]
@sumnerevans dark theme looks nice, the color on the light theme could be a bit bright.

**Comment by alexandrevicenzi** [comment]
Thanks @sumnerevans. PR is merged.
