### ISSUE TITLE
[Firefox] Social -> RSS Icon is not layout properly and seems to be missing icon

### ISSUE THREAD

**Issue by reisub0** [alexandrevicenzi/Flex#235]
Both on my test site and on your [demo site](https://flex.alxd.me/blog), the RSS icon is not displaying properly

![image](https://user-images.githubusercontent.com/25099244/88903357-3032e280-d271-11ea-87f3-f0c9bdb5f34a.png)

**Comment by reisub0** [comment]
This seems to be a Firefox specific issue. Layouts correctly on Chrome.
The icons also seem to be off-center.
![image](https://user-images.githubusercontent.com/25099244/88903853-f1515c80-d271-11ea-9ed2-8e4ebeffcacb.png)

**Comment by alexandrevicenzi** [comment]
It works on my Firefox, both on Linux and Android.

If you use AdBlock, VPN, Proxy, or anything else it may cause the CSS to not load properly, that's not a theme's fault.

**Comment by reisub0** [comment]
You're right Alex. It seems to be due to my AdBlocker. I should have checked that before I raised this issue.

Sorry, closing the issue.

**Comment by alexandrevicenzi** [comment]
You could check console for errors, this could be one of the reasons, maybe some JS is breaking the website.

If there's an error you can post it here so we can take a look and check if it would be possible to fix.

**Comment by reisub0** [comment]
<details><summary>uBlock Origin Logger output</summary>

```
+1
##.fa-rss
flex.alxd.me
dom
https://flex.alxd.me/blog/
```
```
+1
##.adsbygoogle
flex.alxd.me
dom
https://flex.alxd.me/blog/
```
```
+1
##.ads-aside
flex.alxd.me
dom
https://flex.alxd.me/blog/
```
```
+1
||googlesyndication.com^
--
flex.alxd.me
3
script
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
```
```
+1
||googlesyndication.com^
--
flex.alxd.me
3
script
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
```
```
+1
google-analytics.com/analytics.js
<<
flex.alxd.me
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com^
--
flex.alxd.me
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
addthis.com/addthis_widget.js
<<
flex.alxd.me
script
https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55adbb025d4f7e55
```
```
+0
||addthis.com^$3p,important,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs|~sitecore.com|~amd.com
--
flex.alxd.me
3
script
https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55adbb025d4f7e55
```
```
+0
||googlesyndication.com^
--
flex.alxd.me
3
script
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
```
```
+0
https://flex.alxd.me/blog/
```
</details>

Console log just shows this:
![image](https://user-images.githubusercontent.com/25099244/89025166-fbdc2680-d343-11ea-8153-cb8709c97359.png)

**Comment by alexandrevicenzi** [comment]
It seems that there are no errors. I don't really know why it would not load the CSS properly.
