### ISSUE TITLE
Use updated Google fonts API and match fonts specified to fonts used.

### ISSUE THREAD

**Issue by saagit** [alexandrevicenzi/Flex#241]
By examining the source, the weights and styles of fonts used are as follows:

### Source Sans Pro

| font-weight | font-style | File                  | Used for                    |
| :---        | :---       | :---                  | :---                        |
| 300         |            | style.less            | headers, blockquote         |
| 400         |            | user agent stylesheet | body                        |
| 400         | italic     | user agent stylesheet | `<em>`                      |
| 400         | italic     | style.less            | div.figure p.caption        |
| 600         |            | style.less            | .translations .active       |
| 600         |            | style.less            | p.admonition-title          |
| 700         |            | user agent stylesheet | `<strong>`                  |
| 700         | italic     | user agent stylesheet | `<em> <strong>`             |

### Source Code Pro

| font-weight | font-style | File            | Used for      |
| :---        | :---       | :---            | :---          |
| 400         |            | e.g. github.css | e.g. Error    |
| 400         | italic     | e.g. github.css | e.g. Comments |
| 700         |            | e.g. github.css | e.g. Keywords |

The stylesheets for tipuesearch and isso also specify font weights/styles, but do not have requirements beyond what is listed above.

I'm not sure whether the 600 weight is worth specifying, or should be changed in style.less, or should just be left as it is where I assume a fallback weight of 700 is used.

Similarly, I'm not sure if the 700 weight italic style is worth specifying or should just rely on a fallback.

If no change is to be done for the 600 weight nor 700 italic, a change such as the following should be made to drop Source 300 and move to the new API:
```diff
diff --git a/templates/base.html b/templates/base.html
index a43e612..b3f208f 100644
--- a/templates/base.html
+++ b/templates/base.html
@@ -18,7 +18,7 @@
   {% endif %}
 
   {% if USE_GOOGLE_FONTS != False %}
-  <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
+  <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,400;0,700;1,400&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
   {% endif %}
 
   {% if USE_LESS %}
```

**Comment by alexandrevicenzi** [comment]
I guess this looks ok, not that far from the old one, if something is missing in the new version it would probably be in the old one.
