### ISSUE TITLE
Change the order of copyright parameters in the site footer

### ISSUE THREAD

**Issue by jedludlow** [alexandrevicenzi/Flex#244]
The current copyright formatting in the footers is:

    &copy; {{ COPYRIGHT_NAME}} {{ COPYRIGHT_YEAR }}

The more traditional formatting would be to put the year first followed by the name of the copyright holder:

    &copy; {{ COPYRIGHT_YEAR }} {{ COPYRIGHT_NAME }}

Would you accept a pull request that implements this change? I've already got it ready to go.

**Comment by alexandrevicenzi** [comment]
Sure, sounds about right.
