### ISSUE TITLE
Is dark mode really supported?

### ISSUE THREAD

**Issue by mhatta** [alexandrevicenzi/Flex#247]
Dark mode is supposed to be supported (https://github.com/alexandrevicenzi/Flex/wiki/Dark-Mode), but I couldn't find  correspond source.  Is any 3rd party plugin or such required?

**Comment by alexandrevicenzi** [comment]
It should work, visit [https://flex.alxd.me/blog/](https://flex.alxd.me/blog/) go to the bottom of the page and click in dark mode, it will switch colors unless your OS is set to dark mode already, like Gnome, it should auto load in dark mode, so in this case, you can switch to light mode.

**Comment by alexandrevicenzi** [comment]
Dark mode is just CSS and JS, look in `static` folder for the files.

**Comment by mhatta** [comment]
Ah, now I see the problem.  the version of Flex linked from getpelican/pelican-themes repo (v2,2,0, b3bd59002a) is older than the current HEAD, so it doesn't contain new files in `static`.

**Comment by alexandrevicenzi** [comment]
I need to update pelican-themes, it's on my TODO list, will do soon.
