### ISSUE TITLE
Enabling translation does not seem to work

### ISSUE THREAD

**Issue by pchampin** [alexandrevicenzi/Flex#250]
I tried to follow the [instructions for enabling translations](https://github.com/alexandrevicenzi/Flex/wiki/Enable-translation), but all theme labels ("posted on", "continue reading"...) are still displayed in English :cry: .
I tried this on my own site, and on a fresh site created with `pelican-quickstart`.

I'm using Pelican 4.5.0 with Python 3.8.2 ...

**Comment by alexandrevicenzi** [comment]
If nothing is translated is a misconfiguration. If some words are not translated is translation missing, not all languages are complete.

Without your settings, I can't help much.

For French:

```py
# Default theme language.
I18N_TEMPLATES_LANG = "en"

# Your language.
DEFAULT_LANG = "fr"

# Match languages for other configs.
OG_LOCALE = "fr"
LOCALE = ("fr", "fr.utf8")
```

**Comment by pchampin** [comment]
Ok, I got the `I18N_TEMPLATES_LANG` wrong, that's why it didn't work!

I will suggest an explicit warning on the wiki page, because it is easy to get this wrong.

Thanks
