### ISSUE TITLE
Add support for SEO plugin

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/Flex#254]
We could use [SEO plugin](https://github.com/pelican-plugins/seo) instead of this theme SEO, which is not great by the way.

The theme SEO can not be removed, only disabled via configuration.

**Comment by alexandrevicenzi** [comment]
I guess we could close #42 with this change.

**Comment by MaevaBrunelles** [comment]
Hi @alexandrevicenzi,

The last version of SEO plugin supports Open Graph and Twitter Cards, so I can now try to handle this issue.

Based on [this template](https://github.com/alexandrevicenzi/Flex/blob/master/templates/partial/og.html) (for example), I was thinking to develop something like:
```
{% if PLUGINS and 'seo' in PLUGINS %}
       <meta property="og:site_name" content="{{ SITENAME }}"/>
       ...
{% endif %}
```

or add a configuration in `pelicanconf.py` as `DISABLE_FLEX_SEO = True` and:

```
{% if DISABLE_FLEX_SEO %}
       <meta property="og:site_name" content="{{ SITENAME }}"/>
       ...
{% endif %}
```

What do you think?

**Comment by alexandrevicenzi** [comment]
Sounds good.

Moving Flex SEO to partials can help a lot clean up the code and add the seo plugin.

I vote for `IF SEO IN PLUGINS` as a good approach, this ensures that if the plugin is enabled, Flex SEO is disabled.
