### ISSUE TITLE
Pelican plugins submodule

### ISSUE THREAD

**Issue by justinmayer** [alexandrevicenzi/Flex#255]
Hey Alex. Pelican maintainer here. By adding the legacy monolithic Pelican Plugins repository as a submodule in this theme, anybody who follows the instructions listed on the legacy monolithic Pelican Plugins repository README…

    git clone --recursive https://github.com/getpelican/pelican-themes ~/pelican-themes

… will end up with the entire contents of the legacy monolithic Pelican Plugins repository recursively downloaded along with the Flex theme. This is probably not what they want to happen.

Any chance you might consider removing that submodule from the project?

**Comment by alexandrevicenzi** [comment]
Hi Justin, I think it's ok to remove, not sure if it's used anymore. I'll take a look.
