### ISSUE TITLE
Add configuration for Google Analytics 4

### ISSUE THREAD

**Issue by Christian-Cardone** [alexandrevicenzi/Flex#256]
The new Google Analytics (4) uses a different script for tracking as well as new properties IDs. The new measurement ID (from property) is of the form "G-XXXXX" as opposed to the previous Universal Analytics Id that was "UA-XXXXX". So if you create a new Analytics account and want to track your website, you currently can't with the current set up since "UA-XXX" and "G-XXX" are not interchangeable IDs.

To allow users to track their website usage via new Google Analytics 4 its needed to add the new collector script on each page to be tracked.

I've successfully added the configurations needed to let the user use this new feature by inputing their 'GOOGLE_GLOBAL_SITE_TAG' within 'pelicanconf.py'. In the same way they would input their 'GOOGLE_ANALYTICS'  id ('UA-XXX')

The modifications are simple, just modifying the base.html to include the condition that would replicate the collector script across all the pages as well as adding the partial ggst.html file that contains the script.

I'm happy to create a pull request to share those changes.

Summary:

- Add option GOOGLE_GLOBAL_SITE_TAG in pelicanconf
- Add conditional script in base.html to include GOOGLE_GLOBAL_SITE_TAG config
- Add ggst.html containing the script to be replicated across pages

**Comment by alexandrevicenzi** [comment]
Go ahead, send the PR, it can be useful for some people.
