### ISSUE TITLE
Unable to join transifex team

### ISSUE THREAD

**Issue by introt** [alexandrevicenzi/Flex#259]
Hello!

I'd like to translate Flex to Finnish. "Finnish (Finland)" is already listed in the project languages, but it is not available in the "Join team"-dialog's drop-down menu. How to proceed?

**Comment by alexandrevicenzi** [comment]
I had to accept your request, you can translate now. :+1:

**Comment by introt** [comment]
Thanks Alex! I've translated the strings to my best ability (which included taking a short trip to the Finnish blogosphere in order to learn the lingo; while not perfect, imo they're production ready), hope to see them included soon!

**Comment by alexandrevicenzi** [comment]
Thanks, I'll take a look, but it may take some time to get released as there's not much to release now.
