### ISSUE TITLE
Issue with URLs on pages

### ISSUE THREAD

**Issue by Kentoseth** [alexandrevicenzi/Flex#262]
This bug is similar to an Issue I opened 3 years ago: #77 

This is what I have in my `pelicanconf.py`:

```
THEME = 'Flex23'

BROWSER_COLOR = '#333333'
PYGMENTS_STYLE = 'monokai'
ARTICLE_URL = 'posts/{date:%Y}/{date:%b}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'posts/{date:%Y}/{date:%b}/{date:%d}/{slug}/index.html'
PAGE_URL = 'pages/{slug}/'
PAGE_SAVE_AS = 'pages/{slug}/index.html'

DISABLE_URL_HASH = True

MAIN_MENU = True
MENUITEMS = (('Categories', '/categories'),
             ('Tags', '/tags'),)
```

Here is my `publishconf.py`:

```
SITEURL = 'https://kentoseth.tk'
RELATIVE_URLS = False
```

(I just included relevant bits from these files and left out the other bits that don't impact this bug)

If you visit: https://kentoseth.tk/pages/about-me

and look to the left-column menu, there are 2 bugs:

1. The Homepage URL is now: https://kentoseth.tk/pages/about-me (instead of: https://kentoseth.tk)
2. Page URLs now include the URL hash again: https://kentoseth.tk/pages/about-me.html#about-me

This problem does not exist on:

 - Article pages
 - https://kentoseth.tk/pages/*/index.html (if using the index.html at the end of the page)

I tried looking under: `/templates/page.html` to see if I can detect the error, but I found nothing referencing this except for `page.translations`.

**Comment by alexandrevicenzi** [comment]
Add `/` into site url, like `SITEURL = 'https://kentoseth.tk/'`, this should probably fix it.

**Comment by Kentoseth** [comment]
Hello,

I attempted that and Pelican has a setting that removes it:

> pelican content -s publishconf.py 
> WARNING: Removed extraneous trailing slash from SITEURL.

https://github.com/getpelican/pelican/blob/7a6686f4679adabdd690668a4ba7cedaf494e243/pelican/settings.py#L572
