### ISSUE TITLE
CRITICAL: 'JINJA_EXTENSIONS' is undefined

### ISSUE THREAD

**Issue by miralin** [alexandrevicenzi/Flex#268]
I get an error "CRITICAL: 'JINJA_EXTENSIONS' is undefined" when I try to render my site with Pelican. As I understand it's because of replacing JINJA_EXTENSIONS with JINJA_ENVIRONMENT and  that code in Pelican **settings.py**:
```Python
    if 'JINJA_EXTENSIONS' in settings:
        logger.warning('JINJA_EXTENSIONS setting has been deprecated, '
                       'moving it to JINJA_ENVIRONMENT setting.')
        settings['JINJA_ENVIRONMENT']['extensions'] = \
            settings['JINJA_EXTENSIONS']
        del settings['JINJA_EXTENSIONS']
```
So even if I define JINJA_EXTENSIONS in my pelicanconf.py it will be deleted from pelican settings and this code at the top of Flex **base.html** leads to mentioned error. 
```Jinja2
{% if 'jinja2.ext.i18n' not in JINJA_ENVIRONMENT.extensions and 'jinja2.ext.i18n' not in JINJA_EXTENSIONS %}
  {%- macro _(msg) -%}
    {{ msg % kwargs }}
  {%- endmacro -%}
{% endif %}
```

**Comment by alexandrevicenzi** [comment]
Feel free to send a patch fixing this, but AFAIK, it works, unless Pelican changed again....

**Comment by miralin** [comment]
I made some additional investigation because I noticed that above parts of code from Pelican and Flex coexist for a long enough time and I didn't face that error before. I found out that this error appears with Jinja2 release3.x. With Jinja2 release 2.x the command I use doesn't throw any error.
```
pelican content -o output -s publishconf.py
```
I will try to send a patch.

**Comment by skandavivek** [comment]
Same issue as above

**Comment by iliailmer** [comment]
I have the same issue, no idea yet how to get started on a fix.

**Comment by alexandrevicenzi** [comment]
JINJA_EXTENSIONS was dropped in 2016 by Pelican, should have been removed a long time ago.

I fixed it in master branch, and I'll submit a new release to Pelican Themes once I get #267 merged.
