### ISSUE TITLE
tipue_search search improvement

### ISSUE THREAD

**Issue by radoeka** [alexandrevicenzi/Flex#271]
I've my blog running in https://FQDN/blog.

The search template base.html expect the file search.html in the root directory.

The attached patch makes search work for me: [search.zip](https://github.com/alexandrevicenzi/Flex/files/6872678/search.zip)

Commit the patch, please.  The patch was created against Flex-2.4.0.

**Comment by radoeka** [comment]
BTW: the patch can be applied with 'patch -p9 < search.patch'.
It worked fine against the current git version.

**Comment by alexandrevicenzi** [comment]
Feel free to submit the patch as a pull request.

**Comment by radoeka** [comment]
Created PR: https://github.com/radoeka/Flex/pull/2

**Comment by alexandrevicenzi** [comment]
Fixed by #277
