### ISSUE TITLE
article summary improvement for template index.html

### ISSUE THREAD

**Issue by radoeka** [alexandrevicenzi/Flex#272]
When a summary consist of 1 line only, the 'continue reading' button is overlapping with the summary.

The attached patch improves this, and takes care that the index.html shows the 'continue reading' button always at the correct location: [index.zip](https://github.com/alexandrevicenzi/Flex/files/6872705/index.zip).

Patch was created against Flex-2.4.0.

**Comment by radoeka** [comment]
BTW: the patch can be applied with 'patch -p9 < index.patch'.
It worked fine against the current git version.

**Comment by alexandrevicenzi** [comment]
Fell free to submit the patch on a pull request.

**Comment by radoeka** [comment]
> Feel free to submit the patch as a pull request.

I would have done so, if I knew the steps how to make a PR.
Can you provide the steps to make a pull request (I don't have write permission to the Flex repository), please.

**Comment by radoeka** [comment]
PR created https://github.com/radoeka/Flex/pull/1

**Comment by alexandrevicenzi** [comment]
Fixed by #276
