### ISSUE TITLE
Adjust max-width for main article does not work with custom_css

### ISSUE THREAD

**Issue by radoeka** [alexandrevicenzi/Flex#274]
I had/have an issue with a too small page width with the current Flex version in git.  It seems that this is due to the commit that was made for this issue: https://github.com/alexandrevicenzi/Flex/issues/196#issuecomment-815274467 comment at 7 April 2021

I tried the suggestion, made in the issue
> it's not configurable, you would need to override the CSS with a custom one to "fix" on your side.

So that's what I tried.  But I don't get it to work :(  I used, the following css code:
```
@media screen and (min-width: 768px) {
  main {
    article {
      max-width: 760px;
    }
  }
}
```

A bit confusing perhaps with the current code, but I've the max-width changed in style.min.css and set it 1024px.  So my page width at the moment is 1024px.  To test the custom_css code I try to make it smaller to 760px, but that does not work :(

I know that the css file is read in correctly, as I can use it to modify other parts of the website with css code into this file.  

How to modify the page width via the CUSTOM_CSS option?
Would it be possible to make this configurable, as it looks like it is difficult to get it changed?

### Observation
One remark: the CUSTOM_CSS code inserted into the html page is:
   <link href="https://FQDN/blog/extra/custom.css" rel="stylesheet">

While in all other cases it is:
  <link rel="stylesheet" type="text/css" href="https://FQDN/blog/theme/stylesheet/style.min.css">
Type= present and link is at the start (makes it consistent with the other stylesheet lines).  It is working though.

The style.css.less page has (see code snippet above):
@media screen and (min-width: 768px) {

While the max-with is set to 760px.  Is that correct?

**Comment by alexandrevicenzi** [comment]
I can make it work with:

```css
@media screen and (min-width: 768px) {
    main article {
        max-width: 1024px;
    }
}
```

This changes the default 760 to 1024.

Be sure to also set the proper config:

```py
STATIC_PATHS = ["extra/custom.css"]

EXTRA_PATH_METADATA = {
    "extra/custom.css": {"path": "custom.css"},
}

CUSTOM_CSS = "custom.css"
```

Where `extra/custom.css` is the path location of you css file.

**Comment by radoeka** [comment]
Thanks, you css code made it work.  

The PATH settings I had already worked as the css was included in the pages.
Hence, the following is sufficient.
```
STATIC_PATHS = ['extra']
```

I wonder why your code is working, and mine not.  I derived mine from the style.less file.  Is that no real css?
BTW: how or when is the file style.min.css created (I assume it is created from style.less file, is that correct)?

To make it easier for others, would it be possible to have a setting like for example "FLEX_PAGE_WIDTH = 1024px", that would insert the above css code in the style sheet?  Or just create the additional stylesheet?

BTW 2:
While am we're at it: the custom.css stylesheet html code is:
```
<link href="https://fqdn/blog/extra/custom.css" rel="stylesheet">
```

While the other css references have:
```
<link rel="stylesheet" type="text/css" href="https://fqdn/blog/theme/stylesheet/style.min.css">
```
'rel=' at the beginning and customer.css has no 'type='.  Wouldn't it be consistent to make them same.

**Comment by alexandrevicenzi** [comment]
[LESS](https://lesscss.org/) is not CSS. LESS needs a compiler to create the proper CSS.
LESS was popular when this theme was created, but SASS is far better these days IMHO.

I see no reason to add `FLEX_PAGE_WIDTH` as it can be changed used custom CSS, and also 760px is a standard width for readability.

About the consistent, feel free to send a pull request to fix it, but it does not really matter much, most browsers are smart enough to figure out the content type.

**Comment by radoeka** [comment]
Created PR for the CUSTOM_CSS html <link> line (to make it consistent) https://github.com/radoeka/Flex/pull/3  

> LESS is not CSS. 

OK, clear.  Do you maintain both files, style.less and style.min.css?
Or is style.min.css the only one (of the two) used?  
The latter is very difficult to read, as it is all on 1 line.  Would it be possible to make it nicely formatted, so it is easier to read?

**Comment by radoeka** [comment]
Created another PR https://github.com/radoeka/Flex/pull/4 to make the stylesheet style.min.css pass the validator with less errors (although it is already very very clean).  I hope, that this one can be accepted.

**Comment by alexandrevicenzi** [comment]
> Created PR for the CUSTOM_CSS html line (to make it consistent) [radoeka#3](https://github.com/radoeka/Flex/pull/3)
> 
> > LESS is not CSS.
> 
> OK, clear. Do you maintain both files, style.less and style.min.css?
> Or is style.min.css the only one (of the two) used?
> The latter is very difficult to read, as it is all on 1 line. Would it be possible to make it nicely formatted, so it is easier to read?

The project uses Node.JS + Gulp + lessc to create the minified version.
There are some helper scripts to help on that.
