### ISSUE TITLE
Can't get theme working

### ISSUE THREAD

**Issue by Karsteski** [alexandrevicenzi/Flex#282]
Hi, I'm new to Pelican and after reading through the Pelican documentation, as well as how to add Flex as a theme, I still can't get it working. Some of the Pelican themes work fine with my test page, but then others just do nothing. I'm not sure what's going wrong here since I've followed the steps exactly to get themes going... 

Attempting to generate my site gives the following error:

```
WARNING: Caught exception:
  | "'JINJA_EXTENSIONS' is undefined".
```

Which I can solve just by using an an empty dictionary with the same name, but it doesn't change anything.

**Comment by alexandrevicenzi** [comment]
That's not an error, it clearly says WARNING, just something to be aware of.

There's an example of a working blog [here](https://github.com/alexandrevicenzi/Flex/tree/master/docs) and the result is [here](https://flex.alxd.me/), you can use it as a base for your own blog.

Without your configuration or your repository, I can't say anything else.

**Comment by Karsteski** [comment]
Here's the thing though. Even when I copy everything to from docs, where all I change is the output folder to output so I can use `make devserver`, it does not work properly. All I get is the xml files.
[Here's my updated repo](https://github.com/Karsteski/karsteski.github.io/tree/master/pelican)
