### ISSUE TITLE
Can't get theme working

### ISSUE THREAD

**Issue by Karsteski** [alexandrevicenzi/Flex#283]
That's not an error, it clearly says WARNING, just something to be aware of.

There's an example of a working blog [here](https://github.com/alexandrevicenzi/Flex/tree/master/docs) and the result is [here](https://flex.alxd.me/), you can use it as a base for your own blog.

Without your configuration or your repository, I can't say anything else.

_Originally posted by @alexandrevicenzi in https://github.com/alexandrevicenzi/Flex/issues/282#issuecomment-894508401_

**Comment by Karsteski** [comment]
Here's the thing though. Even when I copy everything to from docs, where all I change is the output folder to output so I can use `make devserver`, it does not work properly. All I get is the xml files.
[Here's my updated repo](https://github.com/Karsteski/karsteski.github.io/tree/master/pelican)

**Comment by Karsteski** [comment]
If I literally just download your Flex repo and do `pelican content` + `pelican --listen` then it works. So I guess I have a misunderstanding how pelican is supposed to work? So I guess I can just work backward from your template but I do not understand what I am doing wrong when trying to setup your template... Sorry for the trouble.

**Comment by alexandrevicenzi** [comment]
I don't want to be rude, but honestly, I'm not here to set up your environment, there are examples and the wiki to help out, that's your best choice.

Your website https://www.karsteski.com/ seems to be there and working.

If I can give one piece of advice, move to [Hugo](https://gohugo.io/), it's far better, the documentation is good, not perfect, but compared to Pelican, it offers more features and it's easier to use if you don't know much about coding.

I have [this theme](https://themes.gohugo.io/themes/soho/) for Hugo that looks similar to Flex. If you need some help with Hugo, give me a shout, I may be able to help you.

**Comment by Karsteski** [comment]
> 
> 
> I don't want to be rude, but honestly, I'm not here to set up your environment, there are examples and the wiki to help out, that's your best choice.
> 
> Your website https://www.karsteski.com/ seems to be there and working.
> 
> If I can give one piece of advice, move to [Hugo](https://gohugo.io/), it's far better, the documentation is good, not perfect, but compared to Pelican, it offers more features and it's easier to use if you don't know much about coding.
> 
> I have [this theme](https://themes.gohugo.io/themes/soho/) for Hugo that looks similar to Flex. If you need some help with Hugo, give me a shout, I may be able to help you.

Yea sorry about the neediness, I was just getting angry with how nothing was working like I expected... I got it working after figuring out how the SITEURL worked differently locally vs. deployment, obvious in hindsight but I glazed over it when reading the documentation.

Hugo was originally my first choice, and I may switch to it eventually but now that I have things working, I'll stick to Pelican unless I have more major problems. 

Thank you for your time, and thanks for the great theme :)
