### ISSUE TITLE
Changelog : version 2.3.0 and 2.4.0 are missing

### ISSUE THREAD

**Issue by Linkid** [alexandrevicenzi/Flex#286]
Hi !
I'm using Flex and I've just seen that the changelog is not up to date. Version 2.3.0 and 2.4.0 changelogs are missing, but can be found in the blog.

**Comment by Linkid** [comment]
I've just prepared a PR to update the changelog file. I'll be happy to submit it :).

**Comment by alexandrevicenzi** [comment]
I guess it was forgotten, no harm to update the file. Send your PR.

**Comment by alexandrevicenzi** [comment]
Fixed by #287
