### ISSUE TITLE
Add support for series plugin

### ISSUE THREAD

**Issue by fghaas** [alexandrevicenzi/Flex#289]
I love this theme and would like to port [my site](https://xahteiwi.eu) to it, but I've written quite a few articles as installments of [series](https://github.com/pelican-plugins/series) and I'd prefer not to lose that functionality.

The implementation is fairly simple and can heavily borrow from Series plugin support in other themes (I currently use bootstrap3, and Flex could use the same functionality with minimal modifications).

It currently sits in the `series` topic branch in my fork (https://github.com/fghaas/Flex/tree/series); please let me know if you'd like to entertain a PR. Thank you!

**Comment by alexandrevicenzi** [comment]
I don't mind new plugins as long as they do not break the theme. If you want to add it, ensure that the theme stills works without the plugin.

**Comment by fghaas** [comment]
It does, but don't take my word for it. :) I've put together a small test facility with tox and GitHub workflow actions. It's in https://github.com/fghaas/Flex/tree/tox and you can review a test run in https://github.com/fghaas/Flex/actions/runs/1343307269. Would you like a PR for that as well?
