### ISSUE TITLE
Change aside div img {border-radius & max-width}

### ISSUE THREAD

**Issue by aubindonnot** [alexandrevicenzi/Flex#292]
Hello, 
I have been trying to change the border radius and the size of the profile picture on the template by updating "aside div img {border-radius:50%, max-width: 140px}" under the files Flex-master/static/stylesheet/style & Flex-master/static/stylesheet/style.min with no effects. 
Is there is another callout in the code that need modification?

**Comment by alexandrevicenzi** [comment]
You should put all changes in `CUSTOM_CSS` see https://github.com/alexandrevicenzi/Flex/wiki/Configuration-example
