### ISSUE TITLE
Google fonts are added, even if set to false

### ISSUE THREAD

**Issue by lioman** [alexandrevicenzi/Flex#293]
Google fonts are imported via tipuesearch CSS and `USE_GOOGLE_FONTS` is ignored.

I can implement the fix myself, but want to discuss it first. One simple solution is to just ditch google fonts entirely and add host the fonts. This would be a decrease in configuration complexity, privacy and some say even speed.
With current setup it is easy to be not GDPR compliant and IMHO the risks does not outweigh the proposed benefits.

**Comment by lioman** [comment]
I will implement it like that. But just a side note, there is a recent German court decision that sharing the IP without consent violates tyhe GDPR: https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/

**Comment by alexandrevicenzi** [comment]
Fixed by #294
