### ISSUE TITLE
Add support for stork search via search plugin

### ISSUE THREAD

**Issue by lioman** [alexandrevicenzi/Flex#296]
tipue search is deprecated and [Pelican search](https://github.com/pelican-plugins/search) should be used instead.
I have already implemented it and open this issue, just for discussion purposes.
I can open the PR, once it is documented and tested.

**Comment by alexandrevicenzi** [comment]
Feel free to send a PR and document the new search option as well to notify that tipue is deprecated.

**Comment by alexandrevicenzi** [comment]
BTW, I suggest moving search to a partial template and just include that partial in the base template.

It will become an if/else hell if many search options are used, it's easier to maintain in a partial file for each plugin and another partial for search to glue both plugins.

**Comment by lioman** [comment]
That's one thing I want to do there, before raising an PR. Question about documenting:
Since documentation is in github wiki. Should we document it first and raise a PR then. Or merge the PR and document it later in the wiki. Or last option: Add all documentation about theme settings to README so that code and documentationis always aligned.

**Comment by alexandrevicenzi** [comment]
Fixed by #298
