### ISSUE TITLE
templates/base.html <link> entry with typo href attribute

### ISSUE THREAD

**Issue by slee124565** [alexandrevicenzi/Flex#30]
commit-id : ab0f263d4c7de72cc9123c2bd911260dd9576a38
line 4 <link> entry string
 <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic' rel='stylesheet' type='text/css'>
This <link> 's [href] attribute has invalid value.

**Comment by alexandrevicenzi** [comment]
Where's the typo?

**Comment by slee124565** [comment]
I think there should be 'https:' in the head of href attribute, check the original code :
 <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic' rel='stylesheet' type='text/css'>

**Comment by alexandrevicenzi** [comment]
The code:

`<li><a href="{{ SITEURL }}/{{ related_post.url }}">{{ related_post.title }}</a></li>`

It's Jinja template vars. You need to put your http[s] in `SITEURL` variable.

I see no errors here.

**Comment by sebalix** [comment]
Tip: if you just set `SITEURL = '//example.net'` it will work both with `http:` and `https:` schemes.

**Comment by alexandrevicenzi** [comment]
@sebalix that's true, and it's the best option to use if the blog is under http and https.

**Comment by slee124565** [comment]
sorry that my previous comment did not edit correctly.
we are discussing with different line code
the 4th line in ./templates/base.html
`<link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic' rel='stylesheet' type='text/css'>`
I suppose the href attribute is static reference to internet URI,
and guess there should be a 'https' in head of it's value. like
`<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic' rel='stylesheet' type='text/css'>`

**Comment by alexandrevicenzi** [comment]
@slee124565 as said by @sebalix it's not needed to put http or https if you have `//`. All browsers assume the same schema of the current site if it's only find `//`.

It will fail if you open this template as an html file. If you're hosting somewhere (Python, PHP, etc) it will work.

**Comment by slee124565** [comment]
@alexandrevicenzi  and @sebalix 
Thanks for your explanation.
