### ISSUE TITLE
Mastodon social button not working 

### ISSUE THREAD

**Issue by banym** [alexandrevicenzi/Flex#305]
Not sure why, but the mastodon social button stopped working for me. 

<a class="sc-mastodon" href="https://bsd.network/@banym" target="_blank"><i class="fa fa-mastodon"></i></a>

Not quite sure how to verify what did go wrong or how to help to debug this further.

**Comment by alexandrevicenzi** [comment]
Can you share your config? Nothing changed, so perhaps a configuration issue is the problem.

**Comment by banym** [comment]
yes of course. 
[pelicanconf.py.txt](https://github.com/alexandrevicenzi/Flex/files/9087116/pelicanconf.py.txt)

**Comment by alexandrevicenzi** [comment]
Good, thanks.
