### ISSUE TITLE
Add main content class to make search easy and batter

### ISSUE THREAD

**Issue by paulocoutinhox** [alexandrevicenzi/Flex#308]
Hi,

Please, add main content class to make search easy and batter.

Today the pelican-search plugin get the element "main" or other css selector.

My suggestion is add a class like "main-contents" to the real content div.

Docs:
https://stork-search.net/docs/html

Example of page with Flex theme and empty div class name:

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/395096/182546176-67c183be-85f5-4a0e-998b-38bbf989b5ad.png">

Only add any class like "main-contents" on main div. It will make search better, because using "main" it is indexing the menu, links etc.

Today im using "article div" in "SEARCH_HTML_SELECTOR" to fix this temporally.

Thanks.

**Comment by alexandrevicenzi** [comment]
Hi,

The correct selector would be `article`, all posts are inside an article tag, `main` is meant for the entire website. You can also use the `single` class, as it's applied to articles only.

I'm not sure how the selector works, but it should allow `SEARCH_HTML_SELECTOR = "article.single > div"`, if it does not, well it's a bug in stork. This selector would select only the post content and not the post title, so I suggest using `article` to also select the post title.
