### ISSUE TITLE
Update font-awesome.min.css to be more CSS compliant

### ISSUE THREAD

**Issue by pablomh** [alexandrevicenzi/Flex#31]
Hi,

Updating font-awesome.min.css to currently released version (4.6.1 vs 4.3.0 in Flex) has decreased the number of errors using W3C CSS Validator from 18 to 2.

Best regards.
Pablo

**Comment by alexandrevicenzi** [comment]
Hi @pablomh,

You can send a PR if you want, thanks.

**Comment by pablomh** [comment]
Done: [https://github.com/alexandrevicenzi/Flex/pull/32](url)
