### ISSUE TITLE
Recommend directly cloning this repo?

### ISSUE THREAD

**Issue by peacej** [alexandrevicenzi/Flex#310]
The README says that the best way to install is via [pelican-themes](https://github.com/getpelican/pelican-themes). But that results in installing a version of Flex that is 2 years old. Perhaps you should recommend directly cloning this repo as the best method?

**Comment by alexandrevicenzi** [comment]
Hi, you can clone this, but prefer using one of the git tags, master branch is stable, but something can break unnoticed as there are two many config options that one can use.

**Comment by alexandrevicenzi** [comment]
I also should create a new tag based on the current changes available, will do it soon.

**Comment by alexandrevicenzi** [comment]
Tag v2.5.0 is out.
