### ISSUE TITLE
Canonical link for index page

### ISSUE THREAD

**Issue by paulocoutinhox** [alexandrevicenzi/Flex#314]
Hi,

Google alert me that home (ex: https://mysite.com) has the same canonical link that index.html page (https://mysite.com/index.html). Can you fix adding support to write correct canonical link when index.html is acessed?

Maybe it is here:
https://github.com/alexandrevicenzi/Flex/blob/master/templates/base.html#L103-L117

Thanks.

**Comment by alexandrevicenzi** [comment]
Hi,

Flex supports the Pelican SEO plugin, which does a far better job, you should consider that if SEO is a key requirement, Flex tries to do best SEO practices, but I'm no SEO expert.

I also think that Google should not index *.html, the site index is mysite.com/, and just that, posts are mysite.com/slug.
