### ISSUE TITLE
Tags in pages title

### ISSUE THREAD

**Issue by rsreds** [alexandrevicenzi/Flex#315]
In the theme, the page title is not stripped of tags when used as the page title.
This result in the <p> tag being present in the tab title.
![image](https://user-images.githubusercontent.com/26118849/195803835-5d374c23-d952-4015-a872-2dfd017ac7cc.png)

This is due to the fact that the title is computed as:
`{% block title %} &ndash; {{ page.title }}{% endblock %}`
in the page.html template
This is fixed in the article.html template with
`{% block title %} &ndash; {{ article.title|striptags|escape }}{% endblock %}`

The fix seems simple enough, and I don't see any immediate downside

**Comment by alexandrevicenzi** [comment]
Hi,

I'm not sure why there are HTML tags in the MD meta tags, and I guess that's the issue, but I don't see any harm in stripping the title.

Only generated content from MD should have HTML tags, in this case, the blog post body/content.

Feel free to send a patch fixing this issue.

**Comment by DhwanishShah** [comment]
Hi i want to contribute on this issue. Can you assign me this issue?

**Comment by alexandrevicenzi** [comment]
Fixed by #304
