### ISSUE TITLE
Latex not render in article preview block

### ISSUE THREAD

**Issue by GeorgeHu6** [alexandrevicenzi/Flex#325]
![image](https://user-images.githubusercontent.com/43069137/222041312-0ac73268-2a82-4b43-8184-67bdfa031bbb.png)

just like the screenshot above, my Latex block didn't render in index page

**Comment by alexandrevicenzi** [comment]
This theme has no Latex support, you need a plugin to make it work.

The Latex plugin was never tested with this theme, they may not be fully supported.

**Comment by GeorgeHu6** [comment]
> This theme has no Latex support, you need a plugin to make it work.
> 
> The Latex plugin was never tested with this theme, they may not be fully supported.

OK, that's fine, thank you 😄
