### ISSUE TITLE
Version 3 - Release

### ISSUE THREAD

**Issue by paulocoutinhox** [alexandrevicenzi/Flex#329]
Hi man,

Thanks for this template.

There is a roadmap or release date for version 3?

Im waiting a lot for this :(

Thanks.

**Comment by alexandrevicenzi** [comment]
Hi, no. I'm busy with other things and don't have time to work on this right now.

**Comment by paulocoutinhox** [comment]
Hi man, any news about this great theme?

**Comment by alexandrevicenzi** [comment]
If I had to guess, v3 will be out in late 2024 or 2025.

**Comment by paulocoutinhox** [comment]
Hi, any news? Thanks.

**Comment by alexandrevicenzi** [comment]
No.
