### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by twopercent** [alexandrevicenzi/Flex#331]
Hello,
I started using Flex theme and a few spots I struggled with in the beginning are Social widgets and the logo.

Can you add to the readme a note that Social names need to be Font Awesome icon names? I had put in "git_lab" or something originally and nothing showed up.

Can you add to the readme the pelicanconf.py variable needed to specify the profile image? Something like:
PATH = 'content'
STATIC_PATHS = ['images']
SITELOGO = 'images/profile.jpg'

**Comment by alexandrevicenzi** [comment]
Hi,

The [Wiki](https://github.com/alexandrevicenzi/Flex/wiki) is open, any user should be able to update it.

Many settings come from [Pelican](https://docs.getpelican.com/en/latest/settings.html). The Wiki does not cover what Pelican covers already.

**Comment by twopercent** [comment]
Thank you alexandrevicenzi

I see these settings are already in the Wiki. I had read the README.md and did not see the wiki originally.

**Comment by twopercent** [comment]
Thank you alexandrevicenzi

I see these settings are already in the Wiki. I had read the README.md and did not see the wiki originally.
