### ISSUE TITLE
Links before pages in sidebar [question]

### ISSUE THREAD

**Issue by BasicWolf** [alexandrevicenzi/Flex#333]
Hi @alexandrevicenzi , 

I wanted to display the sidebar LINKS before/on top of the PAGES. However the current template doesn't allow to do so. Would you accept such a code contribution to the theme?

I think a configuration key like `LINKS_BEFORE_PAGES: bool` and some if-elses in the sidebar.html should do the job. 

Thank you for making Flex happen!

**Comment by alexandrevicenzi** [comment]
Hi,

You can override `templates/partial/sidebar.html` on your project and move the code up, there's no need to have a new setting for it.

It's not the best solution, but adding a LINKS_BEFORE_PAGES would require a few ifs/else, and I'm not sure if I would be in favor of that.

**Comment by BasicWolf** [comment]
Thank you! I'll do it as you suggested!
