### ISSUE TITLE
Social icons problem

### ISSUE THREAD

**Issue by dangoron** [alexandrevicenzi/Flex#36]
Hi Alexandre,

I really appreciate your work, it looks perfect on my blog except there were no social icons show up. Finally I noticed the path is not correct.

On file 'base.html' line 14, the href shoud be 
`"{{ SITEURL }}/{{ THEME_STATIC_DIR }}/font-awesome/css/font-awesome.min.css"`
 instead of
 `"{{ SITEURL }}/{{ THEME_STATIC_DIR }}/font-awesome/font-awesome.min.css"`.

Hope this would help.

Best,
Fan Yang

**Comment by alexandrevicenzi** [comment]
This was fixed.

That's a problem when people download master instead of a tag. Most of time the master is broken because I'm working on it.
