### ISSUE TITLE
Improve SEO Tags

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/Flex#42]
Here is a good example: http://demo.ghost.io/style-test/

**Comment by lapmid** [comment]
@alexandrevicenzi  i have to improve meta tags  ,am i right ??

**Comment by alexandrevicenzi** [comment]
@lapmid yeah, if there's something to improve, not sure.

**Comment by alexandrevicenzi** [comment]
Closing this as #267 and #254 added a new SEO plugin.
