### ISSUE TITLE
Theme translations

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/Flex#43]
Pelican supports translation. Flex is only in English, if someone want to use in pt-BR it need to edit the theme.

It's good to not break things if use i18n.

[Jinja way to translate](https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites/localizing_using_jinja2.rst)

**Comment by marcelhuth** [comment]
Hi,
I already have a fork which has i18n included for german language. Unfortunately the fork is very old and I did several changes in other parts - would be nearly impossible to merge all the stuff between my fork and your current master.
I could start over with a new fork and only change the necessary i18n things. As I need this for my own I'll raise a merge request when ready, okay?

**Comment by marcelhuth** [comment]
I've a localized version of the theme, will commit that to my local branch and send a pull request. But, I think the steps necessary for getting all the localization to work with `pybabel`, probably for having another language supported or getting the `pelican.conf` modifications right, should be documented somehow. Probably in repo's wiki, @alexandrevicenzi ?
Plz let me know if that is what you needed. The files generated by `pybabel` will be excluded as those have to be generated if theme changes and are only needed if you want to use a specific localization.

**Comment by alexandrevicenzi** [comment]
@marcelhuth thereś two things to document somewhere.

- How to use translations
- How to translate

Thanks for your effort in this task.

**Comment by marcelhuth** [comment]
Having i18n support in the theme means you **have to** import the i18n_subsites plugin from [pelican-plugins](https://github.com/getpelican/pelican-plugins/tree/master/i18n_subsites) repo and add the JINJA2_EXTENSIONS for i18n as the `{% trans %}` tags have to be interpreted by JINJA2
This would be the only change necessary in your `pelicanconf.py`. The theme will then use the default language which is "en_US", which is exactly the same as now.

If you want to get another language to work there is a little more configuration in pelicanconf.py and, if not yet available, the translation has to be done with `pybabel`. I'll give a full example as soon as the i18n version of your theme is passing the tests (see #46 pull request, still working on that)

**Comment by alexandrevicenzi** [comment]
@marcelhuth I think Jinja uses gettext, so it can be done with any translation tool that supports PO files.

About the pelican plugins, well, it's a very big breaking change. There's any change to run without downloading any extra package for those that will only use English?

I already use pelican plugins, so for me it's not a big deal to include another dependency. But I'm thinking that maybe not all users are using it and forcing to use it's a little bit complicated.

**Comment by alexandrevicenzi** [comment]
@marcelhuth as expected the translation doesn't fit for Portuguese. I think this same problem can occur to any other language, like Spanish or Chinese.

The problem is that `trans` tag from Jinja sucks. There's no `blocktrans` as Django, that let you create some crazy messages.

The simple example:

```html
<p>{% trans %}Built using{% endtrans %} <a href="http://getpelican.com" target="_blank">Pelican</a> - <a href="https://github.com/alexandrevicenzi/flex" target="_blank">Flex</a> {% trans %}theme by{% endtrans %} <a href="http://alexandrevicenzi.com" target="_blank">Alexandre Vicenzi</a></p>
```

In English is:

`Built using Pelican - Flex theme by Alexandre Vicenzi`

But in Portuguese is:

`Publicado através do Pelican - O tema Flex foi criado por Alexandre Vicenzi`

In Django we can do:

```html
<p>{% blocktrans %}Built using {{ some_link }} - {{ another_link }} theme by {{ also_another_link }}{% endblocktrans %}</p>
```

There's a way to [implement this on Jinja](https://github.com/MoritzS/jinja2-django-tags). It could be another Pelican plugin.

**Comment by alexandrevicenzi** [comment]
@marcelhuth I was looking for some inspiration, but 99% of pelican themes doesn't support translation.

I found [one](https://github.com/molivier/nest/tree/master#pelicanconf-example) but this is crazy. And there's [this one](https://github.com/piefa703/pjport) that doesn't has trans block but has translation.

**Comment by marcelhuth** [comment]
@alexandrevicenzi Sorry, I didn't realize that it could be problem with other languages as in german the sequence is nearly the same :(
I've found a "workaround" for this w/o using another plugin in Pelican. You can use variables in Jinja2 even in the `{% trans %}` tags. Please let me know if this could be an option for other languages or at least with Portuguese:
```
<p>{% trans pelican="<a href=\"http://getpelican.com\" target=\"_blank\">Pelican</a>", flex="<a href=\"https://github.com/alexandrevicenzi/flex\" target=\"_blank\">Flex</a>", alexandrevicenzi="<a href=\"http://alexandrevicenzi.com\" target=\"_blank\">Alexandre Vicenzi</a>" %}Built using {{ pelican }} - {{ flex }} theme by {{ alexandrevicenzi }}{% endtrans %}</p>
```
The "variables" (which are more expressions) are substituted with the hyperlink and its text. I guess this is not the best implementation for this as we can't translate the text "Pelican" nor "Flex" inside the link.
See [here](http://jinja.pocoo.org/docs/dev/templates/#i18n-in-templates). This leads to a message.po entry of
```
#: templates/partial/flex.html:1
#, python-format
msgid "Built using %(pelican)s - %(flex)s theme by %(alexandrevicenzi)s"
msgstr "Erstellt mit %(pelican)s - %(flex)s Design von %(alexandrevicenzi)s"
```
where you can "re-arrange" the variables.

Probably we could use the "Newstyle Gettext". This could give a more readable theme? Please let me know if that would work. I'll quickly get a new PR if you like.

**Comment by alexandrevicenzi** [comment]
@marcelhuth Yes, I was thinking about that. The new style has a lot of improvements.

I'm not sure, but I think this is more readable.

```html
{{ gettext('Hello World!') }}
{{ gettext('Hello %(name)s!', name='World') }}
{{ ngettext('%(num)d apple', '%(num)d apples', apples|count) }}
```

About the translations, I was thinking to change some theme messages. So I could ajust what is wrong. But you can also send a PR if you like.

**Comment by marcelhuth** [comment]
Let me look through the stuff. I'll rework the `{% trans %}` tags to some nicer newstyle gettext expressions. For now, I don't think it is necessary to rework the messages of the theme.

If tested a bit, we could use the expression format to have kind of variables that would fit with different language's syntax.

I think I'll be done later today or tomorrow and send you a new PR with the changes.

**Comment by alexandrevicenzi** [comment]
Sure, using named variables is far better.

@marcelhuth I made a wiki for how to [turn on translation](https://github.com/alexandrevicenzi/Flex/wiki/Translation-support).

I'm also searching for a good way to create new translations. I think that it's better to use `gulp`  instead of `pybabel`.

The Flex will have the `.POT` file that is the PO template. To create a new translation we just need to copy the POT to PO. To compile the PO there's a gulp plugin to generate MO.

I think `gulp` is far better because it's used to generate everything in the theme, like less compile and minify.

But you don't need to worry about this, I'll do by myself.

**Comment by alexandrevicenzi** [comment]
@marcelhuth I changed some message. I also changed some code and removed autoscape.

You can join [my channel on gitter](https://gitter.im/alexandre-vicenzi/flex) to talk about. It's new, there's no one there yet. 😛

**Comment by alexandrevicenzi** [comment]
@marcelhuth Good news, there's no need to change anything to use the theme with English. Now only it's required to enable i18n plugin if someone want to use in another language.

This is a good improvement since we wont break any old config. See [this commit](https://github.com/alexandrevicenzi/Flex/commit/723e047addf044a2d40af66d57c2eb5beda544a7).
