### ISSUE TITLE
Question / Feature request : Option to change the orange-ish theme 

### ISSUE THREAD

**Issue by bingoarunprasath** [alexandrevicenzi/Flex#45]
Can I change the overall "orange" theme by modifying conf files in pelicanconf.py ? If not, can you please add a feature for that ?

**Comment by alexandrevicenzi** [comment]
No you can't. You need to change LESS file.

There's no need for a conf for this. You can change the LESS file. If you want you could create a variable.less and import it where it's needed.

**Comment by sebalix** [comment]
@alexandrevicenzi The `CUSTOM_CSS` does the trick, no?
@bingoarunprasath Check the wiki here https://github.com/alexandrevicenzi/Flex/wiki/Configuration-Example
I change the theme for my blog to a green variant: https://usr-src.org/

**Comment by alexandrevicenzi** [comment]
@sebalix thanks, I forgot about this. :+1:

**Comment by bingoarunprasath** [comment]
Thanks @alexandrevicenzi @sebalix
