### ISSUE TITLE
Google AdSense support

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/Flex#47]
Well, it's very common and useful. But the question is: Where must the banners be placed?

It's not good to add 10 banners per page. One is annoying, so it must be something careful, or not done at all.

Just thinking about this today.

**Comment by gustavofoa** [comment]
I think it makes sense a reponsive adsense banner on top/bottom of articles.

I've just implemented it in a fork. I'm going to PR for your apreciation.

**Comment by alexandrevicenzi** [comment]
I think it's good to have more than two options. We could allow up to 5 places somewhere and the user choose where to place.

Fo example:

```python
ADSENSE = {
  'aside': 'some-id',
  'article-bottom': 'another-id',
  //  ....
}
```

**Comment by gustavofoa** [comment]
Nice! Which other places do you think good to add banners?

Do you agree to support only responsible banners?

**Comment by alexandrevicenzi** [comment]
For all pages (Scenario 1):

![image](https://cloud.githubusercontent.com/assets/2637672/18563264/6df4c08a-7b5d-11e6-8e08-aebd3ea60c15.png)

For Home only (Scenario 2):

![image](https://cloud.githubusercontent.com/assets/2637672/18563332/a9956266-7b5d-11e6-8db6-9511c4bd982b.png)

For articles (Scenario 3):

![image](https://cloud.githubusercontent.com/assets/2637672/18563404/e3f4a340-7b5d-11e6-84fa-2293eef33886.png)

Pages doesn't need banners near content I think. Scenario 1 is good.

We can combine scenarios 1 + 2 and 1 + 3.

Just an idea. You can suggest other places too.

**Comment by alexandrevicenzi** [comment]
In my case I think I'll use only aside and article bottom. Two banners are good for me.

But we could allow up to 5 places.

**Comment by gustavofoa** [comment]
Good idea, I'll try to implement it.

**Comment by alexandrevicenzi** [comment]
Here where to place:

Before closing `aside` (inside aside).
Before open `nav`.
After closing `article` (for single page only).
After article for-loop (for home only).

**Comment by gustavofoa** [comment]
Only responsible banners. Right?

**Comment by alexandrevicenzi** [comment]
Not sure how they will work. As far I know AdSense works good with responsible banners, but we need to  try.

For example, aside must be a square banner, not sure if Google will know this. But we can try.

**Comment by gustavofoa** [comment]
The responsible banner, on load time, adapts for the browser. You can see it working here: http://gustavofurtado.com.br/seja-bom-no-essencial-programador.html

Open it in your smartphone and open it in a desktop to see the difference.

![image](https://cloud.githubusercontent.com/assets/3338496/18587460/8c1b8634-7bf8-11e6-8627-b8312d244aa7.png)

![image](https://cloud.githubusercontent.com/assets/3338496/18587486/ad1029bc-7bf8-11e6-803d-a71013fb4e21.png)

![image](https://cloud.githubusercontent.com/assets/3338496/18587515/dca19f76-7bf8-11e6-9525-8a0da65d8417.png)

But when you resize your browser width after load the page, the banner keeps the size adjusted when it loaded.

![image](https://cloud.githubusercontent.com/assets/3338496/18587550/05f4ec2a-7bf9-11e6-8366-30a07dacfd8a.png)

**Comment by alexandrevicenzi** [comment]
Good.

Did you know that you can use Flex in pt_BR (aka HUEHUEHUEBR)?

**Comment by gustavofoa** [comment]
Yes, I know. I've just forgot to configurate. rsrs
