### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/Flex#49]
There's a plugin [tipue_search](https://github.com/getpelican/pelican-plugins/tree/master/tipue_search) to enable some kind of search.

It also could be used Google custom search or anything else.

**Comment by archeranimesh** [comment]
If your planing to integrate tipue_search, kindly read through this.

http://moparx.com/2014/04/adding-search-capabilities-within-your-pelican-powered-site-using-tipue-search/

**Comment by JackMcKew** [comment]
Hey, I've just forked this theme for my own website and integrated tipue-search in. In the coming days, I will clone this repo and create a pull request. I may need someone else to assist with CSS formatting to be in line with the rest of the theme.

Here is my repo with it integrated already: https://github.com/JackMcKew/jackmckew.dev/tree/master/themes/Flex

**Comment by JackMcKew** [comment]
See https://github.com/alexandrevicenzi/Flex/pull/193 for pull request with Tipue search functionality

**Comment by alexandrevicenzi** [comment]
Fixed in #193.
