### ISSUE TITLE
Codeblock displays the whole code on one line

### ISSUE THREAD

**Issue by BridouZ** [alexandrevicenzi/Flex#53]
Hi, I've been using your theme for my blog and I really love it, amazing work.

However I have an issue that I can't manage to fix.

When I write a codeblock in my markdown files :
`````
[Packager]  
Name=Votre Nom  
Email=votre.adresse@email
```

It is displayed only on one line no matter what I do. So it's not really readable.
An example can be found [here](https://www.bloguslibrus.fr/output/posts/2016/07/creer-des-paquets-sous-solus/#creer-des-paquets-sous-solus) 

Do you have an idea ?

PS: I tried several versions of the theme and it's always the same thing...

**Comment by alexandrevicenzi** [comment]
@BridouZ I have no idea, if you could show your code maybe it help.

For example:

&#96;command args&#96; will produce a one line

and

&#96;&#96;&#96;python
def my_code():
  pass
&#96;&#96;&#96;

will produce a multiline.

This is done by markdown itself and the styles are applied by pygments. It's not Flex. Flex only has custom pygments CSS.

**Comment by BridouZ** [comment]
@alexandrevicenzi Ok I managed to solve my issue, thanks a lot.

The extract_toc plugin was messing up the markdown process and I had to add _codehilite_ markdown extensions to bring back codeblock style :)

**Comment by alexandrevicenzi** [comment]
@BridouZ ok. :)
