### ISSUE TITLE
Problem: Images not showing on tag / category pages

### ISSUE THREAD

**Issue by chrisodva** [alexandrevicenzi/Flex#57]
This might be user error on my part - but I can't figure out when I'm doing wrong. You can see an example at http://odonnellweb.com/pelican/tag/baseball.html

The URLs for the inline images are not forming correctly - they need to be absolute I think. However they are coming out of pelican as relative to the root directory for the site, and thus not found on pages like tags and category. Is this a me problem or the theme?

Thanks

**Comment by alexandrevicenzi** [comment]
It's not a theme problem. It's related with your URL.

If you use `images/foo.png` it will get the current path. If you user `/images/foo.png` it will get the current host.

You need to use the complete path to create your URL and append `/` at the start, so it will get always your domain (`domain.com/images/foo.png`).

**Comment by chrisodva** [comment]
Thanks. I got it figured out with your help.
