### ISSUE TITLE
Don't know how to add new code highlight style

### ISSUE THREAD

**Issue by iozephyr** [alexandrevicenzi/Flex#65]
Sorry, I can't understand the [Wiki](https://github.com/alexandrevicenzi/Flex/wiki/Code-Highlight) about how to add new code highlight styles. Can you write more detailed? Thank you very much.

**Comment by alexandrevicenzi** [comment]
You want to change the default highlight of your theme or you want to create a new style?

If you want to create a new style read the docs of Pygments project to understand how styles are created, this is not a part of Flex.

If you want to change to another style just add this to your pelican conf file:

`PYGMENTS_STYLE = 'monokai'` # or any other style.
