### ISSUE TITLE
GitLab Social Icon

### ISSUE THREAD

**Issue by JesusMtnez** [alexandrevicenzi/Flex#72]
Hello,

I'm currently starting my own blog using Pelican and your __awesome__ theme :+1: :tada: .

I've been playing with social icons so far, and I have realized that there is no support for GitLab icon, as there is for GitHub.

I think it would be easy to include an orange background with the [FontAwesome GitLab Icon](http://fontawesome.io/icon/gitlab/), like the following image:

![gitlab-icon-preview](https://cloud.githubusercontent.com/assets/8639179/21647633/5d2a0982-d29b-11e6-8299-820fd527243e.png)

CSS code

```css
ul.social a.sc-gitlab {
    background-color: orange
}
```

I'm not a web developer, so any help or comments are welcome. Would you like this change in a PR?

**Comment by alexandrevicenzi** [comment]
Hello @JesusMtnez, there's no icon on Flex for GitLab as you can see.

To add it's very easy, just add to LESS file and compile it.

GitLab has many colors as you can see [here](https://about.gitlab.com/press/) not sure which one is the best.

**Comment by JesusMtnez** [comment]
Hello @alexandrevicenzi, thank you for the advise. I hope this week I could make an easy PR with this change.

Again, thank you for your awesome work with this theme.

**Comment by alexandrevicenzi** [comment]
If you don't have time I can change it. It's easy, but I'm not sure when I'll do it.

**Comment by alexandrevicenzi** [comment]
@JesusMtnez I added the yellow color for GitLab, the orange is similar to RSS color, so it's better to use a new one.

**Comment by JesusMtnez** [comment]
@alexandrevicenzi Thank you! Updating my blog right now
