### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by JesusMtnez** [alexandrevicenzi/Flex#73]
It would be great to have spanish (from Spain). If you want, I could help you with it (I'm spanish).

**Comment by okelet** [comment]
This is already done (https://github.com/alexandrevicenzi/Flex/tree/master/translations/es_ES/LC_MESSAGES)...

**Comment by JesusMtnez** [comment]
@okelet Thank you! Even I have set my settings to use es_ES, it didn't seem to work. I'll give it a new try later.

**Comment by okelet** [comment]
I have this is my configuration, working OK:

```python
THEME='themes/Flex'
I18N_TEMPLATES_LANG='en'
DEFAULT_LANG='es'
OG_LOCALE='es_ES'
LOCALE='es_ES.UTF-8'
```

**Comment by JesusMtnez** [comment]
Thank you! I'll try it later :smiley:

**Comment by JesusMtnez** [comment]
@okelet @alexandrevicenzi I'm trying, but it doesn't work. Here are my configuration files:

```python
JINJA_ENVIRONMENT = {
  'extensions': ['jinja2.ext.i18n']
}

PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = ['i18n_subsites']

# Default theme language.
I18N_TEMPLATES_LANG = 'en'
# Your language.
DEFAULT_LANG = 'es'
OG_LOCALE = 'es_ES'
LOCALE = 'es_ES.UTF-8'
```

Any help is welcome :sos:

**Comment by alexandrevicenzi** [comment]
@JesusMtnez you're not the only one complaining about this bug. It must be something on Pelican or i18n_subsites plugin due to recent Pelican changes.

Maybe if you try to use an older version of Pelican it should work. Try the 3.6.x and not the 3.7.

**Comment by JesusMtnez** [comment]
@okelet @alexandrevicenzi I have tried with pelican 3.6.3 and it works like charm! Maybe we should open an issue en pelican or pelican-plugins repositories?

**Comment by okelet** [comment]
Yes, I forgot to say that I don't use the last Pelican version, but the previous. I also had lot of problems with the last version of Pelican.

**Comment by JesusMtnez** [comment]
This issue is duplicated in #74
