### ISSUE TITLE
Strange display of URL for articles

### ISSUE THREAD

**Issue by Kentoseth** [alexandrevicenzi/Flex#77]
Here is what I have in pelicanconf.py : 

```
ARTICLE_URL = '{date:%Y}/{date:%b}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = '{date:%Y}/{date:%b}/{date:%d}/{slug}/index.html'
```

The issue is that articles then render as:

> 2016/Dec/15/some-article-link/#some-article-link

The pelican docs use this example and show a different rendering of the URL. Is this an issue with the theme?

The rendering I'd like, as my old blog had, is:

> 2016/Dec/15/some-article-link/

**Comment by alexandrevicenzi** [comment]
@Kentoseth What url do you expect? This is how Flex generate URLs.

**Comment by Kentoseth** [comment]
@alexandrevicenzi 

Apologies for not specifying that in the original post, but I edited my original (I assume as you responded) and would like the URLs to appear as:

> 2016/Dec/15/some-article-link/

(ideally, removing the duplication)

**Comment by alexandrevicenzi** [comment]
The `#` doesn't mean nothing, it's just to place the page in the right position.

Remove it and try to use on mobile, it will show the menu first, this skip the menu and go right to the text that the user want.

**Comment by Kentoseth** [comment]
How do I remove the # appearing entirely? 

I see this in index.html:

```
      <a class="btn" href="{{ SITEURL }}/{{ article.url }}#{{ article.slug }}">{{ _('Continue reading') }}</a>
```

Do I edit/remove: `#{{ article.slug }}` ?

**Comment by alexandrevicenzi** [comment]
Yep, just remove it.

**Comment by Kentoseth** [comment]
Thank you, that fixed it.

For future reference and for anyone else wanting to achieve the same thing, please edit the following files:

- index.html

> remove any reference to `#{{ article.slug }}`

- base.html

> remove any reference to `#{{ page.slug }}`

Thanks @alexandrevicenzi

**Comment by alexandrevicenzi** [comment]
I did this for a reason, I'll not remove. That's why people fork Flex.

I may one day, if someone else complain about this, add a config to remove this.

**Comment by Kentoseth** [comment]
@alexandrevicenzi maybe you misunderstood me, I don't want you to remove it :)

I am just adding information to this issue for anyone else that wants to achieve something similar.

**Comment by alexandrevicenzi** [comment]
Oh. I got it. :)

If someone complain about this again I maybe add a config. it's better.
But 'til now I don't remember if someone asked the same thing.

**Comment by dmytrolitvinov** [comment]
@alexandrevicenzi Hi. I have the same trouble. Do you plan to make config to remove this?

**Comment by alexandrevicenzi** [comment]
@dmytrolitvinov No, but if you want a config you can send a PR.
