### ISSUE TITLE
Uses Schema.org's Blog for Rich Snippets

### ISSUE THREAD

**Issue by gutomaia** [alexandrevicenzi/Flex#80]
I think that using microformats provided by schema.org would improve indexing at google. Allowing google better understand the content of the site. As a tradeoff, google give us back a rich snippet feature.

http://schema.org/Blog
https://search.google.com/structured-data/testing-tool/u/0/
https://www.youtube.com/watch?v=A-kX0Aut-18
https://www.youtube.com/watch?v=TvigPUtUH-0

**Comment by alexandrevicenzi** [comment]
@gutomaia Flex uses JSON-LD to provide better info for Google as you can see [here](https://github.com/alexandrevicenzi/Flex/blob/master/templates/partial/jsonld_article.html).

I think microformats are a mess because they add extra tags to HTML. JSON-LD is more human readable.
