### ISSUE TITLE
Display authors in posts and front page

### ISSUE THREAD

**Issue by geotheory** [alexandrevicenzi/Flex#84]
Thanks for an awesome theme, Alex.  Small issue - there doesn't appear to be any setting to specify the authors of posts in the main feed, or even in the posts themselves.  Is this deliberate?

**Comment by alexandrevicenzi** [comment]
I think there's no code for this.

We could add a setting `SHOW_POST_AUTHOR` and show somewhere near post date.

**Comment by geotheory** [comment]
That would be most welcome, thanks Alex

**Comment by alexandrevicenzi** [comment]
@geotheory I don't have time to do this soon. If you could send a PR I appreciate.

**Comment by rpatel3001** [comment]
PR #168 opened

**Comment by rpatel3001** [comment]
PR #168 closed. Breaks translation support and I don't use it so I'm not interested in continuing.

**Comment by alexandrevicenzi** [comment]
This theme was meant for a single author, if anyone wants multi authors they can send a patch later.

**Comment by kakila** [comment]
Is this still under consideration?

**Comment by kakila** [comment]
I mean even for single authors, how can you display the author name in the post?

**Comment by kakila** [comment]
To add the authors it would be simple as

`By {{ article.authors|join(', ')|escape }}`

However this cannot be translated, and I guess one needs to use Jinja. However my lack of experience doesn't allow me to  understand why this fails

`{{ _(By %(authors), authors=article.authors|join(', ')|escape) }}`

I actually couldn't find a way of using `_()` without erros.

**Comment by alexandrevicenzi** [comment]
It should be `{{ _("By %(authors)", authors=article.authors|join(', ')|escape) }}`, but this fails in many ways.

For multiples authors, it would produce: `By XYZ, ABC, QWERT`

In English the correct is: `By XYZ and ABC` if only two and `By XYZ, ABC, and QWERT` if more than two

For other languages it may follow another pattern.

This could be considered if done properly, but as the theme is meant for ONE single author, the name would be in the sidebar already, not needing anything else IMHO.

**Comment by kakila** [comment]
Well, sometimes a solution is better than none. As far as I know "Authors: " would work in any language that has the meaning of "Authors". This should be written only if there is more than one author.

**Comment by kakila** [comment]
> ONE single author

Then you should put this clearly in the README, and do not allow to render the "Authors" page. Unless, of source, you are happy with that inconsistency. I think if you keep "Authors" page, then you cannot claim it is a purely ONE author theme.

**Comment by alexandrevicenzi** [comment]
@kakila as stated in the readme, this theme is not under development anymore. You are free to fix anything that is broken in a PR, as long as it is a proper fix.

If you want to work on this issue I can re-open it and assign it to you.
