### ISSUE TITLE
Site not translated (with master of 18 febr 2017)

### ISSUE THREAD

**Issue by radoeka** [alexandrevicenzi/Flex#86]
When adding this change 
  https://github.com/ncharlot/Flex/commit/389b3f42fa5fea2ab34ec9698be534fe196dff93
to base.html, the following error is given:

> pelican
CRITICAL: UndefinedError: 'gettext' is undefined

The problem seems to be known and is discussed in 
  https://github.com/getpelican/pelican-themes/issues/460#issuecomment-269821765

Appearantly subsites_i18n is required, or a better solution would be a plugin jinra_i18n providing the gettext dependency.

Anything for Flex that can be done about this.

**Comment by radoeka** [comment]
I installed flex master, the error is now not seen, but the site does not get translated.

Current configuration:
JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}
DEFAULT_LANG = 'de'
OG_LOCALE = 'nl_NL'
LOCALE = 'nl_NL'

**Comment by radoeka** [comment]
after installing the plugin i18n_subsite, the error vanishes and the site gets translated :)

**Comment by alexandrevicenzi** [comment]
Yes, **subsites_i18n** is required. You can create a new plugin that does the same thing, but there's no way of Flex having any python functions to solve this.
