### ISSUE TITLE
Markdown paragraph symbol visible in preview page

### ISSUE THREAD

**Issue by Jorge-S** [alexandrevicenzi/Flex#93]
I'm not sure if this an issue on my end as I am new to pelican in general, but when on the home page the markdown paragraph symbol is visible at all times (should only be visible on hover over). This Markdown text comes from a Jupyter notebook using the ipynb plugin.

![image](https://cloud.githubusercontent.com/assets/25993638/23446715/6aeb47f2-fe0b-11e6-97aa-bc2f729f48bf.png)

However when I am viewing the post the Markdown paragraph symbol is invisible as expected (visible only on hover over functionality is still present, again as expected).

![image](https://cloud.githubusercontent.com/assets/25993638/23446823/311cde0e-fe0c-11e6-890f-390a44fb6937.png)

Thoughts?

**Comment by alexandrevicenzi** [comment]
I have no idea why this happens. Maybe a plugin, maybe some invisible char on your text.

You could try to change the theme and see if happens. You could use another tool to write your content, as VIM, Atom, Sublime or any other.

**Comment by alexandrevicenzi** [comment]
@Jorge-S Have you found a solution?

**Comment by Jorge-S** [comment]
I haven't had a chance to take a look, been out of town. I'm hoping to take a crack at it soon. I'll post what I find.

**Comment by Jorge-S** [comment]
So I ran a different theme and it still shows up. I'm thinking that it has something to do with how Markdown displays headers? Still looking more into it but it's not your theme that's causing it.

**Comment by alexandrevicenzi** [comment]
- Are you on Windows or Linux?
- What browser do you use? Maybe it's a browser plugin
- What plugins do you have on Pelican?
- What text editor do you use?

Ask this questions to yourself, maybe it helps.

**Comment by ix5** [comment]
To generate the article summary all html/css tags are being stripped. The ipython-specific inlined stylesheet is thus not being included when only `article.summary` is being shown, e.g. in the `<meta>description` and preview snippet you posted here.

You could either strip the paragraph sign(`¶`) manually, put a `display: none` directive for `a.anchor-link` in your main stylesheet, or just not include the first header in your ipython notebooks(the article title is already defined by pelican, so why write it down twice?).

**Comment by Jorge-S** [comment]
Thanks @ix5 I appreciate the explanation. I want to try and "fix" it by adding the display: none directive but I am having trouble finding the a.anchor-link section in the theme. [Newbie question] Would you or @alexandrevicenzi be able to help point me in the right direction? There doesn't seem to be a main stylesheet that I can find.

And to your point ix5, the second header being a duplicate was a symptom of me just typing the first thing that came to my head. My concern in the future would be if I have a post that few enough lines that the next header (whatever it may be) would still be visible in the article summary, bringing us back to square 1.

Thanks again!

**Comment by ix5** [comment]
```
a.anchor-link {
    text-decoration: none;
    visibility: hidden;
}
```
Just put this into `style.css`.
The stylesheets are in the [`/static/stylehseet`](https://github.com/alexandrevicenzi/Flex/tree/master/static/stylesheet) folder.

Or into `style.less` if you use less-css and re-compile.

**Comment by Jorge-S** [comment]
@ix5 I added that line into the top of the style.css file located here:
![image](https://cloud.githubusercontent.com/assets/25993638/23841416/0ff0ae04-077b-11e7-9742-d93834f1efa8.png)

as seen below. Yet the paragraph marking is still visible in the article summary view.
![image](https://cloud.githubusercontent.com/assets/25993638/23841395/f4bb41c6-077a-11e7-9fe0-e54eba6d2656.png)

Any thoughts?

Thanks for the help!

**Comment by Jorge-S** [comment]
Sorry, it worked. The page took longer than expected to refresh. Thank you again both you.
