### ISSUE TITLE
Hidden pages get the same value for the `robots` meta tag as non-hidden pages

### ISSUE THREAD

**Issue by olipratt** [alexandrevicenzi/Flex#95]
Hi @alexandrevicenzi ,

Thanks for taking the time to review and accept my last request.

This is more of an enhancement request - Flex users won't want [hidden pages](http://docs.getpelican.com/en/latest/content.html?highlight=hidden#pages) to be indexed by search engines, so this issue proposes a new `ROBOTS_HIDDEN` config option to set the value of the `robots` meta tag to a different value on hidden pages.

I'm going to submit a PR with my fix for review if you want to take this.

**Comment by alexandrevicenzi** [comment]
Well, 'til I know, hidden pages aren't linked anywhere, so how would google find this hidden page if it's not linked in any page neither in the sitemap.xml?

I'm just curious because if google can't find the page there's no need to remove the robots tag.

**Comment by olipratt** [comment]
Hmm - the main use case I had was that you are happy to link the page from elsewhere (e.g. say I link the page here to share some mildly private information) and the indexer would follow that link to find the page, but you still don't want the contents of the page indexed (so you don't want people to find the page by searching for a phrase in the page).

I'm actually not so sure that's going to be relevant to me now - but still doesn't quite seem right that the page is hidden but marked for indexing.

**Comment by alexandrevicenzi** [comment]
I saw your PR. What I would do is, `if hidden_page then robots = noindex, nofollow`

If is hidden we can assume that the user doesn't want to allow bots to scrap this page.

**Comment by olipratt** [comment]
Sounds like a good plan - it removes the extra config option and makes the change simpler and clearer. It changes existing behaviour which is why I went for the new config option initially, but the new behaviour should be what people would expect and won't actively break anything if you are happy with that.

I updated the pull request and retested the change.

**Comment by alexandrevicenzi** [comment]
Fixed by #96 .
