### ISSUE TITLE
Add 'neighbors' plugin support

### ISSUE THREAD

**Issue by olipratt** [alexandrevicenzi/Flex#97]
Hi,

I've been looking at adding support for the [neighbors](https://github.com/getpelican/pelican-plugins/tree/master/neighbors) plugin to Flex, so I can get previous/next post buttons on articles.

If you're happy to accept that (and it won't change anything if you don't enable the plugin) I'll probably submit a PR around the weekend, but the interesting thing is that I think it will add new text - 'Previous Post' and 'Next Post', which I think would need translating - so not sure what the impact of that is or if it's a problem?

Thanks.

**Comment by alexandrevicenzi** [comment]
@olipratt feel free to send a PR.
