### ISSUE TITLE
markdown-css

### ISSUE THREAD

**Issue by chenjiandongx** [alexandrevicenzi/Flex#99]
Hi,I have been using your theme for blog,too.I prefer writing with markdown.
And how can I replace default markdown-css with github-markdown-css.

Do guys have a idea?

**Comment by alexandrevicenzi** [comment]
Could you explain in a better way the problem?

Do you want to change the CSS coding style of your snippets or do you want GitHub flavored markdown support on Pelican?

**Comment by chenjiandongx** [comment]
The latter,but I recently found that the dafault flavored was not bad.So I decide not do change it.Thanks your response. :D
